// GENERATED by `bun run acs:migrations` (packages/prx/scripts/gen-acs-migrations.ts)
// from packages/anchored-chain-sqlite/src/migrations/*.sql. Do not edit by hand —
// edit the .sql migrations (drizzle's source of truth) and regenerate.
//
// Embeds the migration SQL as a string constant so a `bun build --compile` binary
// (no on-disk ./migrations) can materialize the schema, and so the package
// publishes to JSR (which rejects `with { type: "text" }` imports). GH-245.

export const EMBEDDED_MIGRATION_SQL: Record<string, string> = {
  "0000_init": "CREATE TABLE `derivation_inputs` (\n\t`derivation_id` text NOT NULL,\n\t`input_name` text NOT NULL,\n\t`input_digest` text NOT NULL,\n\tPRIMARY KEY(`derivation_id`, `input_name`),\n\tFOREIGN KEY (`derivation_id`) REFERENCES `derivations`(`derivation_id`) ON UPDATE no action ON DELETE no action\n);\n--> statement-breakpoint\nCREATE INDEX `derivation_inputs_digest` ON `derivation_inputs` (`input_digest`);--> statement-breakpoint\nCREATE TABLE `derivation_outputs` (\n\t`derivation_id` text NOT NULL,\n\t`output_name` text NOT NULL,\n\t`output_digest` text NOT NULL,\n\tPRIMARY KEY(`derivation_id`, `output_name`),\n\tFOREIGN KEY (`derivation_id`) REFERENCES `derivations`(`derivation_id`) ON UPDATE no action ON DELETE no action\n);\n--> statement-breakpoint\nCREATE INDEX `derivation_outputs_digest` ON `derivation_outputs` (`output_digest`);--> statement-breakpoint\nCREATE TABLE `derivations` (\n\t`derivation_id` text PRIMARY KEY NOT NULL,\n\t`producer` text NOT NULL,\n\t`manifest_json` text NOT NULL,\n\t`ts` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `ref_log` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`prev_digest` text,\n\t`new_digest` text NOT NULL,\n\t`reason` text NOT NULL,\n\t`ts` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `ref_log_name_ts` ON `ref_log` (`name`,`ts`);--> statement-breakpoint\nCREATE TABLE `refs` (\n\t`name` text PRIMARY KEY NOT NULL,\n\t`digest` text NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
  "0001_tiresome_the_watchers": "ALTER TABLE `derivations` ADD `envelope_json` text;",
};
