import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";

import { findRepoRoot } from "../src/repo-root.ts";
const REPO_ROOT = findRepoRoot();
import { collectDocRelPaths } from "../src/graph/build.ts";

/**
 * Completeness guard for the Markdown surface (mirrors
 * `no-operational-python.test.ts`'s `git ls-files` invariant).
 *
 * Each doc generator already drift-checks its own outputs, and the JSON-LD
 * graph auto-catalogs the docs `collectDocRelPaths()` returns. What nothing
 * guarded before this test: that *every* tracked `.md` is accounted for. A new
 * doc added in an unscanned location — or a new generated doc type without a
 * drift test — used to slip in silently.
 *
 * Rule: every tracked `.md` must be either in the graph doc-catalog
 * (`collectDocRelPaths`) or in the `NON_CATALOGED` exclude list below, which
 * records *why* each excluded file is not cataloged. Adding a `.md` anywhere
 * forces a decision: catalog it, or exclude it with a reason.
 */

// Markdown intentionally NOT in the graph doc-catalog. Dir prefixes cover
// generated/source families; exact paths cover one-offs. Reasons are required.
const NON_CATALOGED_PREFIXES: ReadonlyArray<readonly [string, string]> = [
  [".claude/agents/", "generated by gen-agents.ts; drift-checked in agents/generate.test.ts"],
  [".claude/context/", "generated by gen-claude-context.ts; drift-checked in scripts/claude-context.test.ts"],
  ["packages/prx/community/templates/", "render-community template *sources*, not rendered docs"],
  [".changeset/", "changesets tooling: config README + ephemeral release-note fragments (consumed on version bump)"],
];

const NON_CATALOGED_FILES: Readonly<Record<string, string>> = {
  "CLAUDE.md": "Claude Code project instructions; @imports the generated .claude/context/project.md",
  ".beads/README.md": "beads tool boilerplate",
  ".claude/commands/prx.md": "Claude slash-command definition (config, not project docs)",
  ".github/ISSUE_TEMPLATE/custom.md": "GitHub issue form",
  ".github/PULL_REQUEST_TEMPLATE.md": "generated by render-community",
};

// changesets generates a `packages/<name>/CHANGELOG.md` on every `version`
// bump (one per released package), so match them by rule rather than listing
// each — a new entry must not silently break the doc-catalog gate.
const PACKAGE_CHANGELOG_RE = /^packages\/[^/]+\/CHANGELOG\.md$/;

function trackedMarkdown(): string[] {
  const r = spawnSync("git", ["-C", REPO_ROOT, "ls-files", "*.md"], { encoding: "utf8" });
  expect(r.status, r.stderr ?? "").toBe(0);
  return (r.stdout ?? "").split("\n").filter(Boolean);
}

function isNonCataloged(path: string): boolean {
  if (path in NON_CATALOGED_FILES) return true;
  if (PACKAGE_CHANGELOG_RE.test(path)) return true;
  return NON_CATALOGED_PREFIXES.some(([prefix]) => path.startsWith(prefix));
}

describe("markdown coverage — every tracked .md is accounted for", () => {
  test("no .md is unclassified (catalog it, or add it to NON_CATALOGED with a reason)", () => {
    const catalog = new Set(collectDocRelPaths());
    const unaccounted = trackedMarkdown().filter(
      (p) => !catalog.has(p) && !isNonCataloged(p),
    );
    expect(
      unaccounted,
      "these .md files are neither in the graph doc-catalog (collectDocRelPaths) " +
        "nor in NON_CATALOGED. Either catalog them (docs/, repo-root, spec/README, " +
        "package READMEs) or add an explicit exclusion with a reason:\n" +
        unaccounted.join("\n"),
    ).toEqual([]);
  });

  test("the NON_CATALOGED exclude list has no stale entries", () => {
    const tracked = trackedMarkdown();
    const trackedSet = new Set(tracked);

    const staleFiles = Object.keys(NON_CATALOGED_FILES).filter((p) => !trackedSet.has(p));
    expect(staleFiles, `remove these dead NON_CATALOGED_FILES entries:\n${staleFiles.join("\n")}`).toEqual([]);

    const stalePrefixes = NON_CATALOGED_PREFIXES.filter(
      ([prefix]) => !tracked.some((f) => f.startsWith(prefix)),
    ).map(([prefix]) => prefix);
    expect(stalePrefixes, `remove these dead NON_CATALOGED_PREFIXES:\n${stalePrefixes.join("\n")}`).toEqual([]);
  });

  test("every package CHANGELOG.md is excluded by the changesets rule", () => {
    const changelogs = trackedMarkdown().filter((p) => PACKAGE_CHANGELOG_RE.test(p));
    // The rule must actually match something (else it's dead) and exclude all.
    expect(changelogs.length).toBeGreaterThan(0);
    for (const c of changelogs) expect(isNonCataloged(c)).toBe(true);
  });
});
