// GENERATED-FEATURE SOURCE — the content-addressed derivation-chain claim, as a
// gherkin feature projected from @bounded-systems/anchored-chain's real digest
// behavior. `scripts/gen-derivation-chain-feature.ts` writes
// `features/derivation-chain.feature`; the faithfulness + drift guard is
// `test/provenance/derivation_chain_feature.test.ts`. The baseline manifest and
// per-field mutations below are the SHARED source of truth: the feature's Examples,
// the faithfulness test, and the value_props.ts checks all read them, so the
// gherkin, the test, and the claim cannot diverge.

import {
  type Derivation,
  digestManifest,
  sha256Hex,
} from "@bounded-systems/anchored-chain";

export const DERIVATION_CHAIN_FEATURE_BANNER =
  "# GENERATED by `bun packages/prx/scripts/gen-derivation-chain-feature.ts` from\n" +
  "# @bounded-systems/anchored-chain (digestManifest / canonicalJson / in-toto).\n" +
  "# Do not edit by hand — drift + faithfulness are checked by\n" +
  "# packages/prx/test/provenance/derivation_chain_feature.test.ts.\n";

/** The manifest fields a derivation's content-addressed id is computed over. */
export const MANIFEST_FIELDS = [
  "producer",
  "inputs",
  "outputs",
  "contracts",
  "params",
] as const;
export type ManifestField = (typeof MANIFEST_FIELDS)[number];

/** The baseline manifest every scenario / check mutates from. */
export const BASELINE_MANIFEST: Derivation["manifest"] = {
  producer: "prx://keeper/commit",
  inputs: { source: sha256Hex("baseline-source") },
  outputs: { commit: sha256Hex("baseline-commit") },
  contracts: ["custody/commit-auth"],
  params: { subcommand: "commit" },
};

/** The baseline with exactly one field changed — must change the digest. */
export function mutatedManifest(field: ManifestField): Derivation["manifest"] {
  switch (field) {
    case "producer":
      return { ...BASELINE_MANIFEST, producer: "prx://reviewer/commit" };
    case "inputs":
      return { ...BASELINE_MANIFEST, inputs: { source: sha256Hex("other-source") } };
    case "outputs":
      return { ...BASELINE_MANIFEST, outputs: { commit: sha256Hex("other-commit") } };
    case "contracts":
      return { ...BASELINE_MANIFEST, contracts: ["custody/other"] };
    case "params":
      return { ...BASELINE_MANIFEST, params: { subcommand: "push" } };
  }
}

/** True iff changing every manifest field changes the content-addressed id. */
export function everyFieldIsTamperEvident(): boolean {
  const base = digestManifest(BASELINE_MANIFEST);
  return MANIFEST_FIELDS.every((f) => digestManifest(mutatedManifest(f)) !== base);
}

function examplesTable(headers: string[], rows: string[][]): string[] {
  const widths = headers.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i]!.length)));
  const fmt = (cells: string[]) =>
    "      | " + cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ") + " |";
  return [fmt(headers), ...rows.map(fmt)];
}

/** Render the gherkin feature from the manifest shape + digest behavior. */
export function generateDerivationChainFeature(): string {
  const lines: string[] = [
    DERIVATION_CHAIN_FEATURE_BANNER,
    "Feature: Signed content-addressed derivation chain",
    "  As an auditor of prx's provenance chain",
    "  I want each derivation's id to be the hash of its manifest",
    "  So that tampering with a step changes its identity and cannot be laundered",
    "",
    "  Rule: a derivation's id is content-addressed — any manifest change changes the id",
    "",
    "    Scenario Outline: changing <field> changes the derivation id",
    "      Given the baseline derivation manifest",
    "      When its <field> changes",
    "      Then digestManifest yields a different id",
    "",
    "      Examples: manifest fields",
    ...examplesTable(["field"], MANIFEST_FIELDS.map((f) => [f])),
    "",
    "  Rule: the id is a deterministic function of content, not key order",
    "",
    "    Scenario: the same manifest always yields the same id",
    "      Given the baseline derivation manifest",
    "      Then digestManifest is equal across repeated calls",
    "",
    "    Scenario: reordering manifest keys does not change the id",
    "      Given two manifests with identical content but different key order",
    "      Then their canonical JSON — and thus their id — is equal",
    "",
    "  Rule: the in-toto statement preserves the manifest",
    "",
    "    Scenario: a manifest round-trips through its in-toto statement",
    "      Given the baseline derivation manifest",
    "      When it is converted to an in-toto statement and back",
    "      Then the recovered manifest equals the original",
    "",
  ];
  return lines.join("\n");
}
