// prx-1dz (audit surface) — the provenance verify gate as a generated,
// drift-checked Gherkin `.feature` (docs/capability-orchestrator.md §2). The
// dual of features/capability-ownership.feature: that one projects the
// production-time guard ("who may RUN a subcommand"); this one projects the
// after-the-fact gate ("a signed EFFECT verifies only when produced by an
// owning actor"). Both read the same owner map (`ownersOf`), so the two halves
// of the capability model cannot disagree.
//
// Scope: the verify gate today attests git WRITES (effect-ownership.effectKindOf
// reads `params.subcommand` and treats the tool as git; gh custody effects join
// once forge attests them). The feature therefore enumerates git writes; the
// faithfulness test exercises every role against `verifyEffectOwnership`.

import {
  POLICY_ROLES,
  allowedSubcommands,
  blockedSubcommands,
  isReadOnly,
  ownersOf,
} from "@bounded-systems/policy";

export const PROVENANCE_FEATURE_BANNER =
  "# GENERATED by `bun run features:render` from " +
  "@bounded-systems/policy (ownersOf) + provenance/effect-ownership. Do not edit by " +
  "hand — edit the policy table / verify gate and regenerate. Drift + faithfulness are " +
  "checked by packages/prx/test/provenance/ownership_feature.test.ts.";

/** The git write subcommands the verify gate attests, sorted. */
export function attestedGitWrites(): string[] {
  const acc = new Set<string>();
  for (const role of POLICY_ROLES) {
    for (const sub of allowedSubcommands("git", role)) {
      if (!isReadOnly("git", sub)) acc.add(sub);
    }
  }
  return [...acc].sort();
}

/** Render a Gherkin Examples table with padded columns for readability. */
function examplesTable(headers: string[], rows: string[][]): string[] {
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map((r) => r[i]!.length)),
  );
  const fmt = (cells: string[]) =>
    "      | " + cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ") + " |";
  return [fmt(headers), ...rows.map(fmt)];
}

/** Render the full provenance-ownership `.feature`. */
export function generateProvenanceFeature(): string {
  const lines: string[] = [
    PROVENANCE_FEATURE_BANNER,
    "Feature: Provenance effect ownership",
    "  As an auditor of what prx verifies after the fact",
    "  I want a signed privileged effect to verify only when its producer owns it",
    "  So that a valid signature alone cannot launder an ambient effect",
    "",
    "  Rule: a signed git effect verifies iff produced by an owning actor",
    "",
    `    Scenario Outline: a signed "git <subcommand>" verifies only for its owners <owners>`,
    "      Given a signed effect derivation for \"git <subcommand>\"",
    `      Then a derivation produced by one of "<owners>" verifies`,
    "      And a derivation produced by any other policy role is rejected as an orphan effect",
    "",
    "      Examples: git writes",
  ];
  const rows = attestedGitWrites().map((sub) => {
    const owners = ownersOf("git", sub);
    return [sub, owners.length ? owners.join(", ") : "(no one)"];
  });
  lines.push(...examplesTable(["subcommand", "owners"], rows), "");

  // Hard-blocked git subcommands: a signed effect for one is an orphan by
  // definition (owned by no one), so the gate fails closed even with a signature.
  lines.push(
    "  Rule: a signed effect for a hard-blocked subcommand is always rejected",
    "",
    `    Scenario Outline: a signed "git <subcommand>" is rejected though hard-blocked`,
    "      Given a signed effect derivation for \"git <subcommand>\"",
    "      Then verification is rejected for every actor",
    "",
    "      Examples: hard-blocked git",
  );
  const blockedRows = [...blockedSubcommands("git")].sort().map((sub) => [sub]);
  lines.push(...examplesTable(["subcommand"], blockedRows), "");

  // The two producer edge cases the gate handles explicitly.
  lines.push(
    "  Rule: producer identity decides the verdict",
    "",
    "    Scenario: a non-policy-role producer passes through (no role to enforce yet)",
    '      Given a signed effect derivation for "git push"',
    '      And its producer actor is a session profile "work"',
    "      Then verification passes through",
    "",
    "    Scenario: an unparseable producer is rejected",
    '      Given a signed effect derivation for "git push"',
    '      And its producer builder id is malformed',
    "      Then verification is rejected",
    "",
  );

  return lines.join("\n");
}
