// Tests the CLI-reference GENERATOR, not the committed file. docs/cli.md is a
// generated artifact maintained on main (regenerated by docs:render / the
// auto-docs-PR workflow), deliberately NOT hard-gated on branches: it enumerates
// the live command registry, which main grows constantly, so a committed-vs-
// generated drift check treadmills against the pull_request merge tree. We assert
// the generator's correctness (every registry command is projected) instead.

import { describe, expect, test } from "bun:test";
import { generateCliDoc } from "../../src/cli/docs.ts";
import { prxCommandRegistry } from "../../src/cli/registry.data.ts";

describe("CLI reference generator (docs/cli.md)", () => {
  test("every registry command appears in the generated reference", () => {
    const doc = generateCliDoc();
    for (const c of prxCommandRegistry) {
      expect(doc, `missing command: ${c.name}`).toContain(`\`${c.name}\``);
    }
  });
});
