import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { ensurePrxExcludes } from "../../src/tools/ignore_sync.ts";

type Fixture = {
  root: string;
  work: string;
  excludePath: string;
};

function makeFixture(): Fixture {
  const root = mkdtempSync(join(tmpdir(), "prx-ignore-sync-"));
  const work = join(root, "work");
  spawnSync("git", ["init", "--initial-branch=main", work], { encoding: "utf8" });
  const excludePath = join(work, ".git", "info", "exclude");
  return { root, work, excludePath };
}

function readExclude(path: string): string[] {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8").split(/\r?\n/);
}

let fx: Fixture;
beforeEach(() => {
  fx = makeFixture();
});
afterEach(() => {
  rmSync(fx.root, { recursive: true, force: true });
});

describe("ensurePrxExcludes", () => {
  test("untracked mode adds .pr/ and .prx/ to empty info/exclude", () => {
    const result = ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: false });
    expect(result.excludePath).toBe(fx.excludePath);
    expect(result.excludeRules).toEqual([".pr/", ".prx/"]);
    expect(result.excludeUpdatedRules).toEqual([".pr/", ".prx/"]);
    expect(result.excludeRemovedRules).toEqual([]);

    const lines = readExclude(fx.excludePath);
    expect(lines).toContain(".pr/");
    expect(lines).toContain(".prx/");
  });

  test("tracked mode adds only .pr/ and never .prx/", () => {
    const result = ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: true });
    expect(result.excludeRules).toEqual([".pr/"]);
    expect(result.excludeUpdatedRules).toEqual([".pr/"]);
    const lines = readExclude(fx.excludePath);
    expect(lines).toContain(".pr/");
    expect(lines).not.toContain(".prx/");
  });

  test("tracked mode strips a pre-existing .prx/ entry", () => {
    writeFileSync(
      fx.excludePath,
      "# GENERATED BY wtctl ignore sync\n# DO NOT EDIT\n.wt.*\n.pr/\n.prx/\n",
    );
    const result = ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: true });
    expect(result.excludeRemovedRules).toEqual([".prx/"]);
    const lines = readExclude(fx.excludePath);
    expect(lines).toContain(".pr/");
    expect(lines).toContain(".wt.*");
    expect(lines).not.toContain(".prx/");
  });

  test("untracked mode preserves wtctl-generated entries while ensuring prx rules", () => {
    writeFileSync(
      fx.excludePath,
      "# GENERATED BY wtctl ignore sync\n# DO NOT EDIT\n.wt.*\ndevbox.json\n",
    );
    ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: false });
    const lines = readExclude(fx.excludePath);
    expect(lines).toContain(".wt.*");
    expect(lines).toContain("devbox.json");
    expect(lines).toContain(".pr/");
    expect(lines).toContain(".prx/");
  });

  test("idempotent: a second untracked run reports no updates", () => {
    ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: false });
    const result = ensurePrxExcludes({ repoRoot: fx.work, workspaceTrack: false });
    expect(result.excludeUpdatedRules).toEqual([]);
    expect(result.excludeRemovedRules).toEqual([]);
    const text = readFileSync(fx.excludePath, "utf8");
    expect(text.match(/^\.pr\/$/gm)?.length ?? 0).toBe(1);
    expect(text.match(/^\.prx\/$/gm)?.length ?? 0).toBe(1);
  });
});
