// GENERATED-FEATURE SOURCE — per-work-unit cost visibility, projected from the
// REAL Anthropic usage projector (services/anthropic.ts:projectAnthropicUsage).
// `bun run features:render` writes `features/cost-visibility.feature`;
// the drift + faithfulness guard is `test/services/cost_visibility_feature.test.ts`.
//
// USAGE_FIXTURE (raw usage events) and EXPECTED_BY_UNIT (the per-unit aggregate
// they must project to) are the shared source of truth: the feature's Examples,
// the faithfulness test, and the value_props.ts check all read them, so the
// gherkin, the test, and the claim cannot diverge. The projector is exercised
// over an in-memory SQLite DB — no disk, no ingest run.

import { Database } from "bun:sqlite";

import { projectAnthropicUsage } from "../services/anthropic.ts";

export const COST_VISIBILITY_FEATURE_BANNER =
  "# GENERATED by `bun run features:render` from\n" +
  "# services/anthropic.ts (projectAnthropicUsage, by=workUnitId). Do not edit by\n" +
  "# hand — drift + faithfulness are checked by\n" +
  "# packages/prx/test/services/cost_visibility_feature.test.ts.\n";

type UsageEvent = {
  ts: string;
  workUnitId?: string;
  actor: string;
  input_tokens: number;
  output_tokens: number;
  cache_read_input_tokens: number;
  total_cost_usd: number;
};

/** Raw usage events for two work units (GH-1 twice → aggregation), one unattached. */
export const USAGE_FIXTURE: readonly UsageEvent[] = [
  {
    ts: "2026-05-15T00:00:00Z",
    workUnitId: "GH-1",
    actor: "claude-code",
    input_tokens: 100,
    output_tokens: 50,
    cache_read_input_tokens: 200,
    total_cost_usd: 0.005,
  },
  {
    ts: "2026-05-15T00:01:00Z",
    workUnitId: "GH-1",
    actor: "claude-code",
    input_tokens: 50,
    output_tokens: 25,
    cache_read_input_tokens: 100,
    total_cost_usd: 0.003,
  },
  {
    ts: "2026-05-15T00:02:00Z",
    workUnitId: "GH-2",
    actor: "claude-code",
    input_tokens: 200,
    output_tokens: 100,
    cache_read_input_tokens: 400,
    total_cost_usd: 0.01,
  },
  {
    ts: "2026-05-15T00:03:00Z",
    actor: "claude-code",
    input_tokens: 10,
    output_tokens: 5,
    cache_read_input_tokens: 0,
    total_cost_usd: 0.001,
  },
];

/** The per-unit aggregate USAGE_FIXTURE must project to (the declared truth). */
export const EXPECTED_BY_UNIT: readonly {
  bucket: string;
  calls: number;
  input_tokens: number;
  total_cost_usd: number;
}[] = [
  { bucket: "(unattached)", calls: 1, input_tokens: 10, total_cost_usd: 0.001 },
  { bucket: "GH-1", calls: 2, input_tokens: 150, total_cost_usd: 0.008 },
  { bucket: "GH-2", calls: 1, input_tokens: 200, total_cost_usd: 0.01 },
];

function seededDb(): Database {
  const db = new Database(":memory:");
  db.exec(`
    CREATE TABLE events (
      event_id      TEXT PRIMARY KEY,
      ts            TEXT NOT NULL,
      actor         TEXT NOT NULL,
      action        TEXT NOT NULL,
      uow_id        TEXT,
      artifact_type TEXT,
      artifact_ref  TEXT,
      raw_json      TEXT NOT NULL
    );
  `);
  USAGE_FIXTURE.forEach((e, i) => {
    const raw = JSON.stringify({ kind: "non-interactive-agent", subkind: "usage", ...e });
    db.run("INSERT INTO events VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [
      `e${i}`,
      e.ts,
      e.actor,
      "non-interactive-agent",
      e.workUnitId ?? null,
      null,
      null,
      raw,
    ]);
  });
  return db;
}

/** The REAL projector over the fixture, reduced to the asserted columns. */
export function projectFixtureByUnit(): {
  bucket: string;
  calls: number;
  input_tokens: number;
  total_cost_usd: number;
}[] {
  const db = seededDb();
  try {
    return projectAnthropicUsage(db, { by: "workUnitId" })
      .map((b) => ({
        bucket: b.bucket,
        calls: b.calls,
        input_tokens: b.input_tokens,
        total_cost_usd: b.total_cost_usd,
      }))
      .sort((a, b) => a.bucket.localeCompare(b.bucket));
  } finally {
    db.close();
  }
}

const near = (a: number, b: number) => Math.abs(a - b) < 1e-9;

/** True iff the real projection of the fixture equals EXPECTED_BY_UNIT. */
export function perUnitCostIsVisible(): boolean {
  const got = projectFixtureByUnit();
  if (got.length !== EXPECTED_BY_UNIT.length) return false;
  return EXPECTED_BY_UNIT.every((exp, i) => {
    const g = got[i]!;
    return (
      g.bucket === exp.bucket &&
      g.calls === exp.calls &&
      g.input_tokens === exp.input_tokens &&
      near(g.total_cost_usd, exp.total_cost_usd)
    );
  });
}

function examplesTable(headers: string[], rows: string[][]): string[] {
  const widths = headers.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i]!.length)));
  const fmt = (cells: string[]) =>
    "      | " + cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ") + " |";
  return [fmt(headers), ...rows.map(fmt)];
}

/** Render the gherkin feature from the expected per-unit aggregates. */
export function generateCostVisibilityFeature(): string {
  const attached = EXPECTED_BY_UNIT.filter((b) => b.bucket !== "(unattached)");
  const lines: string[] = [
    COST_VISIBILITY_FEATURE_BANNER,
    "Feature: Per-work-unit cost visibility",
    "  As an operator of a fleet of work units",
    "  I want each unit's token usage and USD cost projected from the audit ledger",
    "  So that I can see what every work unit cost, not just an aggregate",
    "",
    "  Rule: usage events aggregate to a per-work-unit bucket",
    "",
    "    Scenario Outline: <workUnit> usage sums to its own bucket",
    "      Given the recorded usage events",
    "      When usage is projected by workUnitId",
    "      Then <workUnit> shows <calls> calls, <input_tokens> input tokens, and $<total_cost_usd>",
    "",
    "      Examples: per-unit cost",
    ...examplesTable(
      ["workUnit", "calls", "input_tokens", "total_cost_usd"],
      attached.map((b) => [
        b.bucket,
        String(b.calls),
        String(b.input_tokens),
        b.total_cost_usd.toFixed(3),
      ]),
    ),
    "",
    "  Rule: usage with no work unit is still accounted for",
    "",
    '    Scenario: an event with no workUnitId groups as "(unattached)"',
    "      Given a usage event with no workUnitId",
    "      When usage is projected by workUnitId",
    '      Then it appears in the "(unattached)" bucket',
    "",
  ];
  return lines.join("\n");
}
