// prx-8mx — value props as forcing-function-backed claims (bobby's model:
// "smaller forcing functions bubble up to larger value props", and "we can look
// at the code and see how this bit of code gets us to that value prop — helpful
// for pruning and refactoring").
//
// A value prop is a falsifiable claim about what prx does. It is `backed` only
// when each of its forcing functions evaluates true RIGHT NOW (a pure `check`)
// or carries external `evidence` (a merged PR / run). A forcing function that is
// `pending` is a LEARNING GOAL, not a value prop. The doc is GENERATED by
// executing the checks, so a claim cannot overclaim — it goes green only if the
// code actually delivers it.
//
// Each backed forcing function also declares the code it `exercises`. That gives
// the reverse map (code → value props): the refactoring contract (keep the
// forcing function green and the value prop holds regardless of how the code
// changes) and the pruning lens (code that traces to no value prop is a
// candidate to delete).

import { decideAgentToolCall } from "./agents/policy_guard.ts";
import { submitRefFor } from "./submit/artifact.schema.ts";
import { verifyEffectOwnership } from "./provenance/effect-ownership.ts";

export type ForcingFunction =
  // Live + pure — green/red as of now; `exercises` is the code it traces to.
  | { readonly name: string; readonly check: () => boolean; readonly exercises: readonly string[] }
  // Backed by external proof (a merged PR, a recorded run); still traces to code.
  | { readonly name: string; readonly evidence: string; readonly exercises: readonly string[] }
  // A learning goal — not yet backed; `pending` says why. No code trace yet.
  | { readonly name: string; readonly pending: string };

export interface ValueProp {
  /** The bubbled-up claim. */
  readonly claim: string;
  /** The sharp, per-category "why not X". */
  readonly whyNot: string;
  /** The forcing functions that must hold for the claim to be backed. */
  readonly forcing: readonly ForcingFunction[];
}

export const VALUE_PROPS: readonly ValueProp[] = [
  {
    claim: "An agent cannot perform an action its role doesn't own.",
    whyNot:
      "vs raw Claude Code: a delegated capability, not ambient trust — overreach is a denial, not a hope.",
    forcing: [
      {
        name: "forge is denied a git push",
        check: () => decideAgentToolCall({ agentType: "forge", command: "git push origin x" }).allow === false,
        exercises: ["agents/policy_guard.ts:decideAgentToolCall", "agents/policy_guard.ts:parsePolicedCommand", "@bounded-systems/policy:allowedSubcommands"],
      },
      {
        name: "keeper may git push",
        check: () => decideAgentToolCall({ agentType: "keeper", command: "git push origin x" }).allow === true,
        exercises: ["agents/policy_guard.ts:decideAgentToolCall", "@bounded-systems/policy:allowedSubcommands"],
      },
      {
        name: "the orchestrator owns nothing",
        check: () => decideAgentToolCall({ agentType: "orchestrator", command: "git status" }).allow === false,
        exercises: ["agents/policy_guard.ts:decideAgentToolCall", "agents/generate.ts:generateOrchestratorDoc"],
      },
    ],
  },
  {
    claim: "A privileged effect not produced by its owning actor fails verification.",
    whyNot:
      "vs trust-the-signature: a valid signature isn't enough — the producer must OWN the effect, or it's an orphan/ambient effect.",
    forcing: [
      {
        name: "a push produced by reviewer is rejected",
        check: () =>
          verifyEffectOwnership({
            derivationId: "sha256:" + "0".repeat(64),
            manifest: { producer: "prx://reviewer/push", inputs: {}, outputs: {}, contracts: [], params: { subcommand: "push" } },
            ts: 0,
          } as never).ok === false,
        exercises: ["provenance/effect-ownership.ts:verifyEffectOwnership", "provenance/signer.ts:actorFromBuilderId", "@bounded-systems/policy:findOwningRoles"],
      },
    ],
  },
  {
    claim: "A beads work unit can travel intake → merged PR through one signed pipeline.",
    whyNot:
      "vs GitHub Actions: authoring → merge with a content-addressed provenance chain, not CI orchestration.",
    forcing: [
      {
        name: "submit accepts a beads canonical id (not GH-only)",
        check: () => submitRefFor("prx-2c4", "ready") === "prx-2c4:submit@ready",
        exercises: ["submit/artifact.schema.ts:submitRefFor", "submit/artifact.schema.ts:WORK_UNIT_RE"],
      },
      {
        name: "driven end-to-end to a merged PR",
        evidence: "prx-2c4 → PR #85 (merged); chain source@pinned→plan→implement on disk; prx publisher did the merge",
        exercises: ["submit/stage.ts:runSubmitStage", "submit/publish.ts:runSubmitPublish", "pr-state/keeper.ts:runKeeperCommitTree"],
      },
    ],
  },
  {
    claim: "You can see what each work unit cost.",
    whyNot: "vs raw Claude Code: per-actor/unit usage is projected from the audit ledger.",
    forcing: [
      {
        name: "per-unit Anthropic usage is visible",
        pending:
          "verb implemented + runs from source (exit 0), but the released binary errors (prx-eky: schema.sql not embedded) and it needs `prx audit ingest` data",
      },
    ],
  },
];

export type Backing = "backed" | "evidence" | "learning-goal";

export function backingOf(f: ForcingFunction): Backing {
  if ("check" in f) return f.check() ? "backed" : "learning-goal";
  if ("evidence" in f) return "evidence";
  return "learning-goal";
}

/** A value prop is backed iff none of its forcing functions are learning goals. */
export function isValuePropBacked(vp: ValueProp): boolean {
  return vp.forcing.every((f) => backingOf(f) !== "learning-goal");
}

/** The code each forcing function exercises (empty for learning goals). */
export function exercisedBy(f: ForcingFunction): readonly string[] {
  return "exercises" in f ? f.exercises : [];
}

/**
 * The reverse map: code symbol → the value-prop claims it helps deliver. The
 * pruning/refactoring lens — a symbol absent here is unattributed; a green
 * forcing function is the contract a refactor must keep holding.
 */
export function codeToValueProps(): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const vp of VALUE_PROPS) {
    for (const f of vp.forcing) {
      for (const sym of exercisedBy(f)) {
        const arr = map.get(sym) ?? [];
        if (!arr.includes(vp.claim)) arr.push(vp.claim);
        map.set(sym, arr);
      }
    }
  }
  return map;
}

const BANNER =
  "<!-- GENERATED by `bun packages/prx/scripts/gen-value-props.ts` by EXECUTING the " +
  "forcing-function checks in packages/prx/src/value_props.ts. A claim is BACKED only if its " +
  "checks pass right now — it cannot overclaim. Drift-checked by packages/prx/test/value_props.test.ts. " +
  "Do not edit by hand. -->";

function forcingLine(f: ForcingFunction): string {
  const backing = backingOf(f);
  const mark = backing === "backed" ? "✅" : backing === "evidence" ? "📎" : "⚠️";
  const tail =
    "evidence" in f ? ` — ${f.evidence}` : "pending" in f ? ` — learning goal: ${f.pending}` : "";
  const exercises =
    "exercises" in f && f.exercises.length > 0
      ? `\n  - exercises: ${f.exercises.join(", ")}`
      : "";
  return `- ${mark} ${f.name}${tail}${exercises}`;
}

/**
 * Render the value-props doc by EXECUTING every forcing function. The committed
 * doc therefore reflects what the code actually delivers at generation time; the
 * drift test fails if a claim's backing changes without regenerating.
 */
export function generateValuePropsDoc(): string {
  const lines: string[] = [
    "# prx — value props (forcing-function-backed)",
    "",
    BANNER,
    "",
    "Each claim is **backed** only when its forcing functions hold now (a passing pure",
    "check ✅, or external evidence 📎). A ⚠️ forcing function is a **learning goal**, not a",
    "value prop. `exercises` is the code that delivers the claim — the refactoring contract",
    "(keep it green) and the pruning lens (code that traces to nothing is a prune candidate).",
    "",
  ];

  for (const vp of VALUE_PROPS) {
    const status = isValuePropBacked(vp) ? "BACKED" : "LEARNING GOAL";
    lines.push(`## ${vp.claim}  — ${status}`, "");
    lines.push(`**Why not X:** ${vp.whyNot}`, "");
    for (const f of vp.forcing) lines.push(forcingLine(f));
    lines.push("");
  }

  lines.push("## Code → value props (pruning / refactoring lens)", "");
  const reverse = [...codeToValueProps().entries()].sort(([a], [b]) => a.localeCompare(b));
  for (const [sym, claims] of reverse) {
    lines.push(`- \`${sym}\` → ${claims.map((c) => `"${c}"`).join("; ")}`);
  }
  lines.push("");

  return lines.join("\n");
}
