// prx-8mx — value props as forcing-function-backed claims (bobby's model:
// "smaller forcing functions bubble up to larger value props", and "we can look
// at the code and see how this bit of code gets us to that value prop — helpful
// for pruning and refactoring").
//
// A value prop is a falsifiable claim about what prx does. It is `backed` only
// when each of its forcing functions evaluates true RIGHT NOW (a pure `check`)
// or carries external `evidence` (a merged PR / run). A forcing function that is
// `pending` is a LEARNING GOAL, not a value prop. The doc is GENERATED by
// executing the checks, so a claim cannot overclaim — it goes green only if the
// code actually delivers it.
//
// Each backed forcing function also declares the code it `exercises`. That gives
// the reverse map (code → value props): the refactoring contract (keep the
// forcing function green and the value prop holds regardless of how the code
// changes) and the pruning lens (code that traces to no value prop is a
// candidate to delete).

import { decideAgentToolCall } from "./agents/policy_guard.ts";
import { submitRefFor } from "./submit/artifact.schema.ts";
import { verifyEffectOwnership } from "./provenance/effect-ownership.ts";
import {
  canonicalJson,
  digestManifest,
  manifestToStatement,
  statementToManifest,
} from "@bounded-systems/anchored-chain";
import {
  BASELINE_MANIFEST,
  everyFieldIsTamperEvident,
} from "./provenance/derivation_chain_feature.ts";
import { perUnitCostIsVisible } from "./services/cost_visibility_feature.ts";

export type ForcingFunction =
  // Live + pure — green/red as of now; `exercises` is the code it traces to.
  | { readonly name: string; readonly check: () => boolean; readonly exercises: readonly string[] }
  // Backed by external proof (a merged PR, a recorded run); still traces to code.
  | { readonly name: string; readonly evidence: string; readonly exercises: readonly string[] }
  // A learning goal — not yet backed; `pending` says why. No code trace yet.
  | { readonly name: string; readonly pending: string };

export interface ValueProp {
  /** The bubbled-up claim. */
  readonly claim: string;
  /** The sharp, per-category "why not X". */
  readonly whyNot: string;
  /** The forcing functions that must hold for the claim to be backed. */
  readonly forcing: readonly ForcingFunction[];
}

export const VALUE_PROPS: readonly ValueProp[] = [
  {
    claim: "An agent cannot perform an action its role doesn't own.",
    whyNot:
      "vs raw Claude Code: a delegated capability, not ambient trust — overreach is a denial, not a hope.",
    forcing: [
      {
        name: "forge is denied a git push",
        check: () =>
          decideAgentToolCall({ agentType: "forge", command: "git push origin x" }).allow === false,
        exercises: [
          "agents/policy_guard.ts:decideAgentToolCall",
          "agents/policy_guard.ts:parsePolicedCommand",
          "@bounded-systems/policy:allowedSubcommands",
        ],
      },
      {
        name: "keeper may git push",
        check: () =>
          decideAgentToolCall({ agentType: "keeper", command: "git push origin x" }).allow === true,
        exercises: [
          "agents/policy_guard.ts:decideAgentToolCall",
          "@bounded-systems/policy:allowedSubcommands",
        ],
      },
      {
        name: "the orchestrator owns nothing",
        check: () =>
          decideAgentToolCall({ agentType: "orchestrator", command: "git status" }).allow === false,
        exercises: [
          "agents/policy_guard.ts:decideAgentToolCall",
          "agents/generate.ts:generateOrchestratorDoc",
        ],
      },
    ],
  },
  {
    claim: "A privileged effect not produced by its owning actor fails verification.",
    whyNot:
      "vs trust-the-signature: a valid signature isn't enough — the producer must OWN the effect, or it's an orphan/ambient effect.",
    forcing: [
      {
        name: "a push produced by reviewer is rejected",
        check: () =>
          verifyEffectOwnership({
            derivationId: "sha256:" + "0".repeat(64),
            manifest: {
              producer: "prx://reviewer/push",
              inputs: {},
              outputs: {},
              contracts: [],
              params: { subcommand: "push" },
            },
            ts: 0,
          } as never).ok === false,
        exercises: [
          "provenance/effect-ownership.ts:verifyEffectOwnership",
          "provenance/merge-guard.ts:projectProvenanceAxis",
          "provenance/signer.ts:actorFromBuilderId",
          "@bounded-systems/policy:findOwningRoles",
        ],
      },
    ],
  },
  {
    claim: "A beads work unit can travel intake → merged PR through one signed pipeline.",
    whyNot:
      "vs GitHub Actions: authoring → merge with a content-addressed provenance chain, not CI orchestration.",
    forcing: [
      {
        name: "submit accepts a beads canonical id (not GH-only)",
        check: () => submitRefFor("prx-2c4", "ready") === "prx-2c4:submit@ready",
        exercises: [
          "submit/artifact.schema.ts:submitRefFor",
          "submit/artifact.schema.ts:WORK_UNIT_RE",
        ],
      },
      {
        name: "driven end-to-end to a merged PR",
        evidence:
          "prx-2c4 → PR #85 (merged); chain source@pinned→plan→implement on disk; prx publisher did the merge",
        exercises: [
          "submit/stage.ts:runSubmitStage",
          "submit/publish.ts:runSubmitPublish",
          "pr-state/keeper.ts:runKeeperCommitTree",
        ],
      },
    ],
  },
  {
    claim:
      "A derivation's identity is content-addressed: any change to its manifest changes its id.",
    whyNot:
      "vs a mutable build record: the id IS the hash of the manifest, so a step can't be edited after the fact without becoming a different derivation — the chain is tamper-evident.",
    forcing: [
      {
        name: "changing any manifest field changes the derivation id",
        check: () => everyFieldIsTamperEvident(),
        exercises: [
          "provenance/derivation_chain_feature.ts:generateDerivationChainFeature",
          "@bounded-systems/anchored-chain:digestManifest",
          "@bounded-systems/anchored-chain:canonicalJson",
        ],
      },
      {
        name: "the id is deterministic and key-order independent",
        check: () =>
          digestManifest(BASELINE_MANIFEST) === digestManifest(BASELINE_MANIFEST) &&
          canonicalJson({ a: 1, b: 2 }) === canonicalJson({ b: 2, a: 1 }),
        exercises: [
          "@bounded-systems/anchored-chain:digestManifest",
          "@bounded-systems/anchored-chain:canonicalJson",
        ],
      },
      {
        name: "a manifest round-trips through its in-toto statement",
        check: () =>
          canonicalJson(statementToManifest(manifestToStatement(BASELINE_MANIFEST))) ===
          canonicalJson(BASELINE_MANIFEST),
        exercises: [
          "@bounded-systems/anchored-chain:manifestToStatement",
          "@bounded-systems/anchored-chain:statementToManifest",
        ],
      },
    ],
  },
  {
    claim: "You can see what each work unit cost.",
    whyNot: "vs raw Claude Code: per-actor/unit usage is projected from the audit ledger.",
    forcing: [
      {
        name: "the compiled binary opens the audit DB (schema embedded)",
        evidence:
          "prx-eky / #106 — `./dist/prx services status --anthropic` exits 0 with no ENOENT; audit-DB smoke test in prx_binary.test.ts",
        exercises: [
          "audit/store/db.ts:openAuditDb",
          "audit/store/sql-asset.d.ts",
          "scripts/prx-compile.ts",
        ],
      },
      {
        name: "per-unit usage is visible (cost projects to per-work-unit buckets)",
        check: () => perUnitCostIsVisible(),
        exercises: [
          "services/anthropic.ts:projectAnthropicUsage",
          "services/cost_visibility_feature.ts:perUnitCostIsVisible",
        ],
      },
    ],
  },
];

export type Backing = "backed" | "evidence" | "learning-goal";

export function backingOf(f: ForcingFunction): Backing {
  if ("check" in f) return f.check() ? "backed" : "learning-goal";
  if ("evidence" in f) return "evidence";
  return "learning-goal";
}

/** A value prop is backed iff none of its forcing functions are learning goals. */
export function isValuePropBacked(vp: ValueProp): boolean {
  return vp.forcing.every((f) => backingOf(f) !== "learning-goal");
}

/** Fully backed = every FF is a live pure check that passes right now (no evidence items). */
export function isFullyBacked(vp: ValueProp): boolean {
  return vp.forcing.every((f) => "check" in f && f.check());
}

/** Evidence-backed = backed (no learning goals) but at least one FF is evidence, not a live check. */
export function isEvidenceBacked(vp: ValueProp): boolean {
  return isValuePropBacked(vp) && !isFullyBacked(vp);
}

/** The code each forcing function exercises (empty for learning goals). */
export function exercisedBy(f: ForcingFunction): readonly string[] {
  return "exercises" in f ? f.exercises : [];
}

/**
 * The reverse map: code symbol → the value-prop claims it helps deliver. The
 * pruning/refactoring lens — a symbol absent here is unattributed; a green
 * forcing function is the contract a refactor must keep holding.
 */
export function codeToValueProps(): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const vp of VALUE_PROPS) {
    for (const f of vp.forcing) {
      for (const sym of exercisedBy(f)) {
        const arr = map.get(sym) ?? [];
        if (!arr.includes(vp.claim)) arr.push(vp.claim);
        map.set(sym, arr);
      }
    }
  }
  return map;
}
