/**
 * Lima driver (GH-211) — render an {@link ExecutorSpec} to a **Lima 2.0**-valid
 * `lima.yaml`.
 *
 * This is prx owning the VM config instead of inheriting `lima-devshell`'s
 * template, which predates Lima 2.0 and trips two `limactl` warnings:
 *   - top-level `guestAgent` is an *unknown field* in Lima 2.0 → omitted here,
 *   - top-level `rosetta` is *deprecated* → emitted under `vmOpts.vz.rosetta`.
 *
 * The output is plain text built field-by-field for our known schema (no YAML
 * dependency, readable result), and is checked against `limactl validate` in the
 * tests so "valid Lima 2.0, zero warnings" is enforced, not assumed.
 */

import { ExecutorSpecSchema, type ExecutorDriver, type ExecutorSpec } from "./spec.ts";

/** A YAML double-quoted scalar — JSON string syntax is a valid YAML 1.2 scalar. */
function dq(value: string): string {
  return JSON.stringify(value);
}

/**
 * Render a multi-line script as a YAML block scalar body indented under
 * `script: |`. Blank lines are preserved as empty (un-indented) lines, which a
 * block scalar reads as blanks.
 */
function blockScalar(script: string, indent: string): string[] {
  return script
    .replace(/\n+$/, "")
    .split("\n")
    .map((line) => (line.length ? `${indent}${line}` : ""));
}

/**
 * Render an {@link ExecutorSpec} to a Lima 2.0 `lima.yaml`. Validates the spec at
 * the seam (throws on a malformed spec) so a bad input never yields half-config.
 */
export function renderLima(spec: ExecutorSpec): string {
  const s = ExecutorSpecSchema.parse(spec);
  const lines: string[] = [
    "# Generated by prx (executor spec → Lima driver, GH-211). Do not hand-edit.",
    "vmType: vz",
  ];

  if (s.arch) lines.push(`arch: ${s.arch}`);

  if (s.images?.length) {
    lines.push("images:");
    for (const img of s.images) {
      lines.push(`  - location: ${dq(img.location)}`);
      if (img.arch) lines.push(`    arch: ${img.arch}`);
    }
  }

  if (s.cpus !== undefined) lines.push(`cpus: ${s.cpus}`);
  if (s.memoryGiB !== undefined) lines.push(`memory: ${dq(`${s.memoryGiB}GiB`)}`);
  if (s.diskGiB !== undefined) lines.push(`disk: ${dq(`${s.diskGiB}GiB`)}`);

  if (s.mounts?.length) {
    lines.push("mounts:");
    for (const m of s.mounts) {
      lines.push(`  - location: ${dq(m.location)}`);
      if (m.mountPoint) lines.push(`    mountPoint: ${dq(m.mountPoint)}`);
      if (m.writable !== undefined) lines.push(`    writable: ${m.writable}`);
    }
  } else {
    lines.push("mounts: []");
  }

  if (s.ssh) {
    lines.push("ssh:");
    if (s.ssh.localPort !== undefined) lines.push(`  localPort: ${s.ssh.localPort}`);
    if (s.ssh.loadDotSSHPubKeys !== undefined)
      lines.push(`  loadDotSSHPubKeys: ${s.ssh.loadDotSSHPubKeys}`);
    if (s.ssh.forwardAgent !== undefined) lines.push(`  forwardAgent: ${s.ssh.forwardAgent}`);
  }

  if (s.env && Object.keys(s.env).length) {
    lines.push("env:");
    for (const [key, value] of Object.entries(s.env)) lines.push(`  ${key}: ${dq(value)}`);
  }

  if (s.provision?.length) {
    lines.push("provision:");
    for (const step of s.provision) {
      lines.push(`  - mode: ${step.mode}`);
      lines.push("    script: |");
      lines.push(...blockScalar(step.script, "      "));
    }
  }

  // Lima 2.0: rosetta lives under vmOpts.vz, NOT as a top-level (deprecated) key.
  if (s.rosetta) {
    lines.push("vmOpts:", "  vz:", "    rosetta:", `      enabled: ${s.rosetta.enabled}`);
    if (s.rosetta.binfmt !== undefined) lines.push(`      binfmt: ${s.rosetta.binfmt}`);
  }

  if (s.mountType) lines.push(`mountType: ${dq(s.mountType)}`);
  if (s.mountInotify !== undefined) lines.push(`mountInotify: ${s.mountInotify}`);

  return `${lines.join("\n")}\n`;
}

/** The Lima runtime driver. */
export const limaDriver: ExecutorDriver = {
  id: "lima",
  render: renderLima,
};
