// CLI reference, projected from the verb registry. Another surface off the same
// source the dispatcher, MCP toolset, and help text use (docs/prx/cli-from-spec.md):
// `prxCommandRegistry` (the CommandSpecs) + `prxActorRegistry` render to
// `docs/cli.md`, so the documented surface cannot drift from the registry. The
// same registry can project a Claude-plugin surface (see `toClaudePlugin`).

import { type CommandDomain, type CommandSpec } from "./registry.ts";
import { prxActorRegistry, prxCommandRegistry } from "./registry.data.ts";

export const CLI_DOCS_BANNER =
  "<!-- GENERATED by `bun run cli:render` (the `prx docs --only cli` verb) from the prx " +
  "command registry (src/cli/registry.data.ts). Do not edit by hand — edit the registry and " +
  "regenerate (`bun run cli:render`). Not a hard CI gate (the command set grows on " +
  "main faster than a branch can track); regenerated on main by the auto-docs-PR " +
  "workflow and unit-tested by test/cli/docs.test.ts. -->";

const DOMAIN_ORDER: readonly CommandDomain[] = ["work-units", "state", "repo-plumbing", "system"];
const DOMAIN_TITLE: Record<CommandDomain, string> = {
  "work-units": "Work units",
  state: "State",
  "repo-plumbing": "Repo plumbing",
  system: "System",
};

// Escape for a Markdown table cell. Backslashes first, then pipes — otherwise a
// literal `\` in the input would combine with the pipe escape (incomplete
// escaping).
const cell = (s: string) => s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|");

// Locale-INDEPENDENT name sort: localeCompare's ordering varies with the
// runner's ICU/locale (hyphens/spaces in names like `commit-tree`/`plan session`
// sort differently), which made the generated doc drift between environments.
const byName = <T extends { name: string }>(a: T, b: T): number =>
  a.name < b.name ? -1 : a.name > b.name ? 1 : 0;

function commandRow(c: CommandSpec): string {
  const flags = [
    c.args ? "args" : "",
    c.binding !== "none" ? c.binding : "",
    c.deprecation ? `deprecated → \`${c.deprecation.alias_for}\`` : "",
    c.internal ? "internal" : "",
  ]
    .filter(Boolean)
    .join(", ");
  return `| \`${cell(c.name)}\` | ${cell(c.description)} | ${c.actor} | ${flags || "—"} |`;
}

/** Render the full CLI reference. */
export function generateCliDoc(): string {
  const lines: string[] = [
    "# prx — CLI reference",
    "",
    CLI_DOCS_BANNER,
    "",
    `\`prx\` exposes **${prxCommandRegistry.length}** commands across ${DOMAIN_ORDER.length} domains,`,
    `owned by **${prxActorRegistry.length}** actors. Each command is a registry entry; the`,
    "CLI, MCP toolset, help text, and this page are all projections of it.",
    "",
  ];

  for (const domain of DOMAIN_ORDER) {
    const cmds = prxCommandRegistry.filter((c) => c.domain === domain).sort(byName);
    if (cmds.length === 0) continue;
    lines.push(
      `## ${DOMAIN_TITLE[domain]}`,
      "",
      "| Command | Description | Actor | Notes |",
      "| --- | --- | --- | --- |",
      ...cmds.map(commandRow),
      "",
    );
  }

  lines.push(
    "## Actors",
    "",
    "The roles that own commands. `dispatchable` actors may be delegated to by the",
    "callers listed (object-capability inbound list).",
    "",
    "| Actor | Summary | Dispatchable | Allowed callers |",
    "| --- | --- | --- | --- |",
    ...[...prxActorRegistry]
      .sort(byName)
      .map(
        (a) =>
          `| ${a.name} | ${cell(a.summary ?? "—")} | ${a.dispatchable ? "yes" : "no"} | ${
            a.allowedCallers.length ? a.allowedCallers.join(", ") : "—"
          } |`,
      ),
    "",
  );

  return lines.join("\n");
}
