// Render `.claude/context/project.md` — a committed, drift-checked context doc
// for Claude sessions — from the JSON-LD project graph (`src/graph/`) plus the
// root package.json scripts. A local (gitignored) CLAUDE.md can `@import` it so
// it auto-loads, while the committed file stays verifiable in CI.
//
// Everything here is projected from existing sources, so the doc can never go
// stale: the `prx docs` verb (--check) and the markdown drift tests
// fail if it drifts from the graph or the scripts.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { getRepoRoot } from "../repo-root.ts";
const REPO_ROOT = getRepoRoot();
import { CLI_PACKAGE, buildGraph, shortName } from "../graph/build.ts";
import { isDocNode, isPackageNode, isProjectNode } from "../graph/model.ts";

export const CONTEXT_OUTPUT = resolve(REPO_ROOT, ".claude/context/project.md");

const BLOB_SPLIT = "/blob/main/";

/** Commands surfaced to Claude: [shown command, gloss, required package.json script?]. */
const COMMANDS: ReadonlyArray<{ cmd: string; gloss: string; script?: string }> = [
  { cmd: "bun install", gloss: "install workspace deps" },
  { cmd: "bun test", gloss: "run the test suite" },
  { cmd: "bun run typecheck", gloss: "tsc --noEmit", script: "typecheck" },
  { cmd: "bun run prx:build", gloss: "compile dist/prx", script: "prx:build" },
  {
    cmd: "bun run docs:render",
    gloss: "regenerate community files, prx.jsonld, README",
    script: "docs:render",
  },
  {
    cmd: "bun run docs:check",
    gloss: "fail on doc drift (also `prx ci --phase=docs`)",
    script: "docs:check",
  },
];

/** Assert every referenced script still exists, so a rename fails the build. */
function assertScripts(): void {
  const pkg = JSON.parse(readFileSync(resolve(REPO_ROOT, "package.json"), "utf8")) as {
    scripts?: Record<string, string>;
  };
  const scripts = pkg.scripts ?? {};
  const missing = COMMANDS.map((c) => c.script)
    .filter((s): s is string => Boolean(s))
    .filter((s) => !(s in scripts));
  if (missing.length > 0) {
    throw new Error(
      `claude-context references missing package.json scripts: ${missing.join(", ")}`,
    );
  }
}

/** The full rendered context doc for the current sources. */
export function renderContextDoc(): string {
  assertScripts();
  const graph = buildGraph();
  const project = graph["@graph"].find(isProjectNode);
  if (!project) throw new Error("project graph has no project node");
  const packages = graph["@graph"].filter(isPackageNode);
  const docs = graph["@graph"].filter(isDocNode);

  const cli = packages.find((p) => p.name === CLI_PACKAGE);
  if (!cli) throw new Error(`graph missing CLI package ${CLI_PACKAGE}`);
  const libraries = packages
    .filter((p) => p.name !== CLI_PACKAGE)
    .sort((a, b) => shortName(a.name).localeCompare(shortName(b.name)));

  const pkgLines = [cli, ...libraries]
    .map((p) => `- \`${p.name}\` — ${p.description.replace(/\.$/, "")}`)
    .join("\n");

  const docLines = docs
    .map((d) => ({ title: d.name, path: d.url.split(BLOB_SPLIT)[1] ?? d.url }))
    .sort((a, b) => a.path.localeCompare(b.path))
    .map((d) => `- ${d.title} — \`${d.path}\``)
    .join("\n");

  const cmdLines = COMMANDS.map((c) => `- \`${c.cmd}\` — ${c.gloss}`).join("\n");

  return `<!--
  Generated by \`bun run claude-context:render\` from prx.jsonld (the project
  graph) and the root package.json scripts. Edit those sources — not this file.
  \`bun run claude-context:check\` (and \`prx ci --phase=docs\`) fail on drift.
-->
# ${project.name} — project context for Claude

${project.name} — ${project.slogan}. A Bun + TypeScript monorepo,
licensed under \`${project.license.identifier}\`.

- \`packages/prx/\` — the CLI
- \`packages/*\` — the \`@bounded-systems/*\` libraries it builds on
- \`spec/\` — the effect/contract spec; \`docs/\` — design docs & ADRs

## Packages

${pkgLines}

## Docs

${docLines}

## Commands & workflow

${cmdLines}

Docs are **generated** from \`packages/prx/community/community.json\`, each
package's \`description\`, and the project graph — then projected into the
community files, \`prx.jsonld\`, the \`README\`, and this context doc. Edit the
sources, never the generated outputs; \`prx ci --phase=docs\` enforces it.
`;
}
