#!/usr/bin/env bash
# bd CLI wrapper — interception layer for ai-home-local bd corrections:
#   * blocks `bd config set <key> ...` when <key> is secret-shaped (GH-1117)
#   * auto-resolves GITHUB_TOKEN for `bd github ...` from `gh auth token` (GH-1123)
#   * rewrites bd's misleading `auto-export: git add failed` warning into an
#     explicit "skipped, not failed" line (GH-1112)
# Everything else runs the upstream bd binary unchanged.
#
# Rationale: bd v1.0.3 stores `bd config set` writes in `.beads/config.yaml`,
# which is tracked. Secret-shaped values must not land on disk in a tracked
# path. Tracked upstream as a structural fix in gastownhall/beads; this wrapper
# is the CLI-boundary defense in ai-home until that lands. See GH-1117.
#
# Contract:
#   $REAL_BD must point to the upstream bd binary. The home-manager
#   wrapper (nix/home-manager/beads.nix) sets it to ${beads-pkg}/bin/bd.
#   The script refuses to run without REAL_BD rather than fall back to
#   PATH — that would re-resolve to this wrapper and recurse forever.

set -euo pipefail

if [[ -z "${REAL_BD:-}" ]]; then
  echo >&2 "bd-wrapper: REAL_BD is unset; refusing to recurse via PATH"
  exit 2
fi

# Auto-resolve GITHUB_TOKEN for `bd github ...` from `gh auth token`.
#
# bd v1.0.3+ accepts GITHUB_TOKEN env or a tracked-config token (which the
# config-set gate below blocks). v1.0.0 auto-detected from `gh auth token`;
# upstream regressed and has not restored the shell-out (gastownhall/beads
# cmd/bd/github.go reads only env+config as of main @ 2026-05-01).
#
# This branch mirrors src/tools/bd.ts:resolveBeadsGitHubSyncEnv: short-circuit
# when GITHUB_TOKEN is already set; otherwise inject from `gh auth token` when
# it succeeds with non-empty stdout. Failures and empty/whitespace stdout pass
# through unchanged so bd's own auth error surfaces to the operator.
#
# Tracked: GH-1123. Retire when upstream restores auto-detect.
if [[ $# -ge 1 && "$1" == "github" && -z "${GITHUB_TOKEN:-}" ]]; then
  if command -v gh >/dev/null 2>&1; then
    gh_token_raw=""
    gh_token_raw="$(gh auth token 2>/dev/null)" || gh_token_raw=""
    gh_token="${gh_token_raw#"${gh_token_raw%%[![:space:]]*}"}"
    gh_token="${gh_token%"${gh_token##*[![:space:]]}"}"
    if [[ -n "$gh_token" ]]; then
      export GITHUB_TOKEN="$gh_token"
    fi
    unset gh_token_raw gh_token
  fi
fi

# Only `config set` is gated. `config get`, `config unset`, `config list`,
# and every other subcommand pass through unchanged.
if [[ $# -ge 3 && "$1" == "config" && "$2" == "set" ]]; then
  key="$3"
  # Case-insensitive match against secret-shaped key fragments.
  shopt -s nocasematch
  if [[ "$key" =~ (token|password|secret|credential|api[._-]?key|access[._-]?key) ]]; then
    shopt -u nocasematch
    cat >&2 <<EOF
bd-wrapper: refusing to write secret-shaped key '$key' via 'bd config set'.

bd v1.0.3 stores config writes in .beads/config.yaml, which is tracked in git.
Writing a secret here would leak it on the next commit.

Use an environment variable instead. For 'bd github ...', this wrapper already
auto-resolves GITHUB_TOKEN from 'gh auth token' when the env var is unset
(GH-1123). Configure other secrets through home-manager / 1Password, not
through 'bd config set'.

Tracked: GH-1117 (this guard) and gastownhall/beads (upstream config split).
EOF
    exit 1
  fi
  shopt -u nocasematch
fi

# Run bd, leaving stdout and stdin untouched, but filter stderr to rewrite the
# misleading `auto-export: git add failed` warning into a "skipped, not failed"
# line.
#
# Why: bd v1.0.3 runs a `git add .beads/issues.jsonl` after every write
# (`export.git-add` defaults true). `.beads/` is git-excluded in every ai-home
# clone (.git/info/exclude, regenerated by `wtctl ignore sync`; required by the
# GH-444 detached-`mainx` invariant), so that `git add` always fails. bd
# swallows git's stderr and prints a bare `Warning: auto-export: git add failed:
# exit status 1` — which fires immediately after the write with no success
# marker of its own, so it reads as "the write failed" (it didn't; only the
# export-to-git side-effect did). The 2026-05-11 mainx incident: an operator saw
# this line, retried `bd create`, and created a phantom duplicate bead.
#
# `.beads/config.yaml` sets `export.git-add: false` to stop the doomed `git add`
# at the source (GH-1112); this filter is belt-and-suspenders for any residual
# noise from sibling code paths (e.g. the `backup.*` JSONL-backup hook) and
# rewrites the wording regardless. The wrapper never sees git's own stderr (bd
# swallows it before printing the bare warning), so it can only contextualize,
# not surface the underlying error — that's gastownhall/beads#3504.
#
# Exit code: the filter must not shadow bd's status, so capture it from
# PIPESTATUS. errexit is relaxed for the pipeline so a non-zero bd exit reaches
# the `exit` below instead of aborting the script first. stdin stays connected
# to bd (bd is non-interactive in practice, but don't introduce a regression).
status=0
set +e
{
  "$REAL_BD" "$@" 2>&1 1>&3 3>&- | awk '
    # Collapse the doomed "git add .beads/..." block into one explicit message.
    # In practice bd swallows the underlying git stderr and only prints the bare
    # Warning line (gastownhall/beads#3504), so the companion-line rules below
    # are belt-and-suspenders for any bd build that lets those lines through.
    /auto-export: git add failed/ {
      print "bd-wrapper: auto-export to git skipped — .beads/ is git-excluded in this repo by design"
      print "(Dolt is canonical; round-trip is `bd github sync`). The bd write above still succeeded."
      print "See GH-1112 / GH-1471."
      next
    }
    /^The following paths are ignored by one of your \.gitignore files:$/ { next }
    /^[ \t]*\.beads(\/[^ \t]*)?$/ { next }
    /^hint: Use -f if you really want to add them\.$/ { next }
    { print }
  ' 1>&2
  status=${PIPESTATUS[0]}
} 3>&1
exit "$status"
