#!/usr/bin/env bun
/**
 * claims_sample — enumerate every PUBLIC claim prx makes from its own sources
 * and emit a markdown scoring template for the claims-calibration audit
 * (see docs/claims-audit-instrument-v0.md for the full rubric).
 *
 * Usage:
 *   bun run packages/prx/scripts/claims_sample.ts [--write PATH] [--force]
 *
 * Unlike audit_sample.ts (which SAMPLES N closed beads), this ENUMERATES the
 * full claim cohort — a claim left out of the cohort is a claim never audited,
 * so the audit only works if the cohort is generated, not hand-listed. The
 * sources are exactly the surfaces a reader trusts:
 *
 *   - the README/marketing tagline       (community/community.json → project.description)
 *   - the headline claims                 (community/community.json → project.claims)
 *   - the value props + forcing functions (src/value_props.ts → VALUE_PROPS)
 *   - the "one sanctioned X" package      (packages/<leaf>/package.json → description)
 *     descriptions
 *   - the STATUS rollup                   (generated by gen-value-props.ts)
 *
 * For value props, the script records the SELF-REPORTED backing tier
 * (backed / evidence / learning-goal) as a *hint* — the audit's whole job is to
 * check whether that self-report matches live enforcement. A claim that
 * self-reports [backed] but is only Partial in the field is exactly the
 * miscalibration this instrument exists to catch.
 *
 * The script intentionally does NOT score. Scoring is judgment (Enforced /
 * Partial / Aspirational / Stale); the script scaffolds the cohort and leaves
 * the verdicts blank, mirroring audit_sample.ts.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { VALUE_PROPS, backingOf, type ForcingFunction } from "../src/value_props.ts";

type ParsedArgs = { writePath: string | null; force: boolean };

// Repo root = three levels up from packages/prx/scripts/.
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..", "..", "..");

/**
 * Phrases that mark a package description as an EXCLUSIVITY / SANCTIONING claim
 * ("the one allowed access point"). These are the descriptions the audit must
 * reconcile against real enforcement — convention + lint is not "the one
 * allowed" if 13 files quietly import around it.
 */
const SANCTIONING_RE = /\bone (sanctioned|allowed)\b|\bsingle sanctioned\b|\bsole\b|\bthe only\b/i;

function parseArgs(argv: string[]): ParsedArgs {
  let writePath: string | null = null;
  let force = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--write") {
      const next = argv[i + 1];
      if (!next) throw new Error("--write requires a path argument (file or directory)");
      writePath = next;
      i++;
    } else if (arg === "--force") {
      force = true;
    } else if (arg === "-h" || arg === "--help") {
      console.log("Usage: bun run packages/prx/scripts/claims_sample.ts [--write PATH] [--force]");
      console.log("See docs/claims-audit-instrument-v0.md for the scoring rubric.");
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return { writePath, force };
}

function resolveWritePath(raw: string, today: string): string {
  let looksLikeDir = raw.endsWith("/");
  if (!looksLikeDir) {
    try {
      looksLikeDir = statSync(raw).isDirectory();
    } catch {
      // Doesn't exist yet; fall back to extension heuristic.
    }
  }
  if (looksLikeDir || !raw.toLowerCase().endsWith(".md")) {
    return join(raw, `claims-${today}.md`);
  }
  return raw;
}

interface CommunityProject {
  project?: { tagline?: string; description?: string; claims?: string[] };
}

function loadCommunity(): CommunityProject["project"] {
  const path = join(REPO_ROOT, "packages/prx/community/community.json");
  const parsed = JSON.parse(readFileSync(path, "utf8")) as CommunityProject;
  if (!parsed.project) throw new Error(`community.json has no project block (${path})`);
  return parsed.project;
}

/**
 * Split the marketing description into auditable clauses. Each clause is a
 * separate promise — "verified against its signed owner" and "through one
 * signed, content-addressed pipeline" are scored independently because they can
 * be enforced independently.
 */
function taglineClauses(description: string): string[] {
  return description
    .split(/[,;:]| — |\bdriving\b|\bwhose\b/)
    .map((c) => c.trim())
    .filter((c) => c.length > 12);
}

interface PackageClaim {
  pkg: string;
  description: string;
}

function loadSanctioningPackageClaims(): PackageClaim[] {
  const pkgsDir = join(REPO_ROOT, "packages");
  const out: PackageClaim[] = [];
  for (const entry of readdirSync(pkgsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifest = join(pkgsDir, entry.name, "package.json");
    if (!existsSync(manifest)) continue;
    let json: { name?: string; description?: string };
    try {
      json = JSON.parse(readFileSync(manifest, "utf8"));
    } catch {
      continue;
    }
    const description = json.description ?? "";
    if (SANCTIONING_RE.test(description)) {
      out.push({ pkg: json.name ?? entry.name, description });
    }
  }
  return out.sort((a, b) => a.pkg.localeCompare(b.pkg));
}

function backingHint(f: ForcingFunction): string {
  const b = backingOf(f);
  return b === "backed"
    ? "self-reports [backed]"
    : b === "evidence"
      ? "self-reports [evidence]"
      : "self-reports [learning goal]";
}

const VERDICT = "- **Verdict:** [ ] Enforced   [ ] Partial   [ ] Aspirational   [ ] Stale";
const GAP = "- **Gap (required unless Enforced):**";
const TRACKING = "- **Tracking bd id (required unless Enforced):**";

function formatCohort(): string {
  const today = new Date().toISOString().slice(0, 10);
  const community = loadCommunity();
  const lines: string[] = [];

  lines.push(`# Claims-calibration audit — ${today}`, "");
  lines.push("Instrument: `docs/claims-audit-instrument-v0.md`. Cohort GENERATED from sources by");
  lines.push(
    "`packages/prx/scripts/claims_sample.ts` — do not hand-edit the claim list; re-run to refresh.",
  );
  lines.push("");
  lines.push(
    "Score each claim into exactly one verdict (Enforced / Partial / Aspirational / Stale).",
  );
  lines.push(
    "Every non-Enforced claim MUST name its gap and a tracking bd id, or it is not audited —",
  );
  lines.push(
    "it is merely noticed. The self-reported backing is a HINT to reconcile against, not a verdict.",
  );
  lines.push("");

  // ── Section A: the marketing tagline, clause by clause ──────────────────
  lines.push("## A. Marketing surface — `community/community.json` → `project`", "");
  if (community?.tagline) {
    lines.push(`### Tagline — "${community.tagline}"`, "");
    lines.push("- **Source:** community.json `project.tagline`");
    lines.push(VERDICT, GAP, TRACKING, "");
  }
  if (community?.description) {
    lines.push("### Description clauses", "");
    lines.push(`> ${community.description}`, "");
    for (const clause of taglineClauses(community.description)) {
      lines.push(`#### "${clause}"`, "");
      lines.push("- **Source:** community.json `project.description` (clause)");
      lines.push(VERDICT, GAP, TRACKING, "");
    }
  }
  for (const claim of community?.claims ?? []) {
    lines.push(`### Headline claim — "${claim}"`, "");
    lines.push("- **Source:** community.json `project.claims[]`");
    lines.push(VERDICT, GAP, TRACKING, "");
  }

  // ── Section B: value props + their forcing functions ────────────────────
  lines.push("## B. Value props — `src/value_props.ts` → `VALUE_PROPS`", "");
  for (const vp of VALUE_PROPS) {
    lines.push(`### "${vp.claim}"`, "");
    lines.push(`- **Why not X:** ${vp.whyNot}`);
    lines.push("- **Source:** value_props.ts (value prop)");
    lines.push(VERDICT, GAP, TRACKING, "");
    for (const f of vp.forcing) {
      lines.push(`#### forcing — ${f.name}`, "");
      lines.push(`- **Self-report:** ${backingHint(f)}`);
      if ("check" in f)
        lines.push("- **Check kind:** live pure `check()` — passes/fails at generation time");
      else if ("evidence" in f)
        lines.push(`- **Check kind:** external evidence (no live test) — ${f.evidence}`);
      else
        lines.push(
          `- **Check kind:** learning goal — ${("pending" in f && f.pending) || "(unstated)"}`,
        );
      if ("exercises" in f && f.exercises.length)
        lines.push(`- **Exercises:** ${f.exercises.join(", ")}`);
      lines.push(VERDICT, GAP, TRACKING, "");
    }
  }

  // ── Section C: "one sanctioned X" package descriptions ──────────────────
  lines.push("## C. Exclusivity claims — `packages/*/package.json` → `description`", "");
  lines.push("These descriptions assert a *sole sanctioned access point*. Reconcile each against");
  lines.push("the seam's real enforcement (lint/depcruise/extractability test) AND its escapes —");
  lines.push('a silent import around the seam makes "the one allowed" false as written.', "");
  for (const { pkg, description } of loadSanctioningPackageClaims()) {
    lines.push(`### \`${pkg}\``, "");
    lines.push(`> ${description}`, "");
    lines.push(`- **Source:** ${pkg}/package.json \`description\``);
    lines.push(VERDICT, GAP, TRACKING, "");
  }

  // ── Section D: the STATUS rollup ────────────────────────────────────────
  const backedCount = VALUE_PROPS.filter((vp) =>
    vp.forcing.every((f) => backingOf(f) !== "learning-goal"),
  ).length;
  lines.push("## D. STATUS rollup — `STATUS.md` (generated)", "");
  lines.push(`### "${backedCount} of ${VALUE_PROPS.length} value props backed"`, "");
  lines.push("- **Source:** STATUS.md (generated by gen-value-props.ts)");
  lines.push(
    '- **Calibration question:** does the rollup read as "nothing left to prove"? Cross-check',
  );
  lines.push("  against the open backlog (`prx beads ready`). A 5/5 with a long backlog is the");
  lines.push(
    "  vocabulary artifact the instrument flags (learning goal = unbacked forcing function,",
  );
  lines.push("  NOT roadmap-complete).");
  lines.push(VERDICT, GAP, TRACKING, "");

  // ── Tally ────────────────────────────────────────────────────────────────
  lines.push("## Tally", "");
  lines.push("Fill after scoring (counts of each verdict, plus the calibration ratio):", "");
  lines.push("- Enforced: ");
  lines.push("- Partial: ");
  lines.push("- Aspirational: ");
  lines.push("- Stale: ");
  lines.push("- **Calibration ratio** (Enforced / total): ");
  lines.push(
    "- **Self-report mismatches** (claims self-reporting [backed] but scored Partial/Aspirational): ",
  );
  lines.push("");

  return lines.join("\n");
}

function main(): void {
  const { writePath, force } = parseArgs(process.argv.slice(2));
  const rendered = formatCohort();

  if (writePath === null) {
    process.stdout.write(rendered);
    return;
  }
  const today = new Date().toISOString().slice(0, 10);
  const target = resolveWritePath(writePath, today);
  mkdirSync(dirname(target), { recursive: true });
  // Atomic exclusive create (no existsSync→write gap): "wx" fails with EEXIST if
  // the file already exists, so a scorer never loses a half-finished audit to a
  // concurrent run. --force overwrites with the default flag.
  try {
    writeFileSync(target, rendered, force ? undefined : { flag: "wx" });
  } catch (err) {
    if (!force && (err as NodeJS.ErrnoException).code === "EEXIST") {
      console.error(
        `claims_sample: refusing to overwrite existing file ${target} (pass --force to replace it)`,
      );
      process.exit(2);
    }
    throw err;
  }
  console.log(target);
}

try {
  main();
} catch (err) {
  console.error((err as Error).message);
  process.exit(1);
}
