#!/usr/bin/env bun
/**
 * Generator for `jsr-manifest.generated.ts` — the static package list that
 * `jsr-sync` projects to JSR.
 *
 * Why generated: `jsr-sync` must NOT read the filesystem itself. A runtime
 * `readFileSync` whose result flows into an outbound request trips CodeQL's
 * `js/file-access-to-http` ("outbound network request depends on file data").
 * By baking the metadata into a compiled-in constant here — this script reads
 * files and writes a file (file → file, never file → network) — `jsr-sync`
 * consumes a static import and stays clean.
 *
 * Reads each `packages/<x>/jsr.json` (+ the sibling `package.json` description)
 * and emits the typed `JSR_PACKAGES` constant.
 *
 * Run: `bun run jsr:manifest`  (drift is guarded by jsr-manifest.generated.test.ts)
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptsDir = dirname(fileURLToPath(import.meta.url)); // packages/prx/scripts
const packagesDir = join(scriptsDir, "..", ".."); // packages/
const OUT = join(scriptsDir, "jsr-manifest.generated.ts");

/** The repo whose GitHub Actions OIDC is authorised to publish (monorepo today). */
const DEFAULT_REPO = { owner: "bounded-systems", name: "prx" } as const;

// Runtime compatibility (informational, shown on the JSR package page).
// Bun is verified for every package — the repo runs on Bun. node/deno/etc. are
// only claimed where verified, to avoid overclaiming: `proc` uses `Bun.spawn`
// (Bun-specific), so it keeps the bun-only default. Add an entry here as a
// package is verified on more runtimes.
const DEFAULT_COMPAT: Record<string, boolean> = { bun: true };
const RUNTIME_COMPAT: Record<string, Record<string, boolean>> = {
  // cas uses only node:crypto + Buffer — portable across the node-compatible runtimes.
  cas: { node: true, deno: true, bun: true },
};

export interface JsrPackageMeta {
  name: string;
  scope: string;
  pkg: string;
  description?: string;
  repo: { owner: string; name: string };
  runtimeCompat?: Record<string, boolean | null>;
}

/** Read every packages/<x>/jsr.json into the typed manifest (sorted by name). */
export function buildManifest(): JsrPackageMeta[] {
  const out: JsrPackageMeta[] = [];
  for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(packagesDir, entry.name);
    if (!existsSync(join(dir, "jsr.json"))) continue;
    const jsr = JSON.parse(readFileSync(join(dir, "jsr.json"), "utf8")) as {
      name?: string;
      githubRepository?: { owner: string; name: string };
      runtimeCompat?: Record<string, boolean | null>;
    };
    const m = /^@([a-z0-9][a-z0-9-]*)\/([a-z0-9][a-z0-9-]*)$/.exec(jsr.name ?? "");
    if (!m) {
      console.warn(`skip ${entry.name}: jsr.json name is not a valid @scope/pkg (${jsr.name})`);
      continue;
    }
    const pj = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as {
      description?: string;
    };
    out.push({
      name: jsr.name!,
      scope: m[1]!,
      pkg: m[2]!,
      ...(pj.description ? { description: pj.description } : {}),
      repo: jsr.githubRepository ?? { ...DEFAULT_REPO },
      runtimeCompat: jsr.runtimeCompat ?? RUNTIME_COMPAT[m[2]!] ?? DEFAULT_COMPAT,
    });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

/** Render the manifest module source (stable output for the drift guard). */
export function renderManifest(pkgs: JsrPackageMeta[]): string {
  return `// GENERATED by scripts/gen-jsr-manifest.ts — do not edit.
// Regenerate: bun run jsr:manifest
//
// jsr-sync imports this static constant instead of reading the filesystem, so
// its outbound requests do not depend on a runtime file read.

export interface JsrPackageMeta {
  name: string;
  scope: string;
  pkg: string;
  description?: string;
  repo: { owner: string; name: string };
  runtimeCompat?: Record<string, boolean | null>;
}

export const JSR_PACKAGES: readonly JsrPackageMeta[] = ${JSON.stringify(pkgs, null, 2)};
`;
}

if (import.meta.main) {
  const pkgs = buildManifest();
  writeFileSync(OUT, renderManifest(pkgs));
  console.log(`wrote ${OUT} (${pkgs.length} packages)`);
}
