#!/usr/bin/env bun
/**
 * gen-jsr-status — render docs/jsr-publishing.md from the JSR manifest + the
 * `READY` set in jsr-publish.ts. The doc is the handoff for prx-zavp (make the
 * held packages JSR-publishable): static guidance + a generated table of which
 * packages auto-publish vs. are held, so the status can't drift from the gate.
 *
 *   bun run jsr:status          # write docs/jsr-publishing.md
 *   bun run jsr:status --check  # fail if the doc is stale (CI drift guard)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { load, READY, topo } from "./jsr-publish.ts";

const DOC = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "docs", "jsr-publishing.md");

/** The static handoff prose. The package table below it is generated. */
const PROSE = `# JSR publishing — status & handoff

<!-- GENERATED by \`bun run jsr:status\` (packages/prx/scripts/gen-jsr-status.ts)
from the JSR manifest + the READY set in jsr-publish.ts. Do not edit by hand —
edit the generator (prose) or the READY set (status), then regenerate. -->

\`@bounded-systems/*\` packages publish to **JSR** (jsr.io), not npm — tokenless
OIDC, GitHub-verified provenance. \`release.yml\` runs \`bun run jsr:publish\`
(\`packages/prx/scripts/jsr-publish.ts\`) on every push to \`main\`: it publishes
any package whose current \`jsr.json\` version isn't on JSR yet, in dependency
order, idempotently.

Only packages in the \`READY\` set auto-publish. The rest are **held** (skipped,
not failed) so a release stays green — they have real \`jsr publish\` blockers.
**The work (prx-zavp): fix each blocker, then add the package to \`READY\`.**

## Per-package loop

1. \`cd packages/<pkg> && bunx jsr publish --dry-run --allow-dirty\` — read the error.
2. Fix the blocker (categories below).
3. Re-run until it prints \`Success\`.
4. Add \`"<pkg>"\` to the \`READY\` set in \`packages/prx/scripts/jsr-publish.ts\`.
5. Regenerate this doc: \`bun run jsr:status\`. One PR per package (or a small batch).

\`bun run jsr:publish --all --dry-run\` ignores the gate — use it to re-discover
which packages now pass once their dependencies are published (the cascade unblocks).

## Blocker categories

- **\`import attribute type "text" is unsupported\`** — a \`.sql\`/text file imported
  via \`with { type: "text" }\`. Codegen the file into a \`*.generated.ts\` string
  constant (mirror \`gen-jsr-manifest.ts\`) and import that. Start with
  \`anchored-chain-sqlite\` (\`src/store.ts\` migrations) — its deps are already published.
- **\`Following packages don't exist\`** — depends on an intra-scope package not yet
  on JSR; unblocks once that dependency is in \`READY\` and published.
- **per-package** — triage each \`jsr publish\` error (\`node:\` builtins in the public
  API, slow types, unsupported syntax). A package at version \`0.0.0\` needs a
  changeset bump before it should publish.

## Gotchas

- Don't add \`?limit=\` to the JSR \`/versions\` API — it returns an empty page, so the
  dedup check thinks nothing is published and re-publish attempts error.
- CodeQL \`js/file-access-to-http\` is a hard gate: never let a file-read value flow
  into a fetch URL — build request URLs from the manifest constants.
- New scripts under \`packages/prx/scripts/\` must be added to \`SCRIPT_BASELINE\` in
  \`packages/prx/test/architecture/scripts-delegate.test.ts\`.
- A \`packages/\` change needs a changeset; run bun via \`nix develop .#jsr\`.

Manual single-package publish: push a \`@bounded-systems/<pkg>@<version>\` tag, or
\`gh workflow run publish-jsr.yml -f package=<pkg>\`.
`;

export function render(): string {
  const ordered = topo(load());
  const rows = ordered.map((p) => {
    const status = READY.has(p.pkg) ? "✅ ready" : "⏳ held";
    const deps = p.deps.length ? p.deps.map((d) => `\`${d}\``).join(", ") : "—";
    return `| \`${p.name}\` | ${p.version} | ${status} | ${deps} |`;
  });
  const ready = ordered.filter((p) => READY.has(p.pkg)).length;
  const held = ordered.length - ready;
  return `${PROSE}
## Package status

${ready} ready, ${held} held — of ${ordered.length} publishable packages.

| Package | Version | Auto-publish | Intra-scope deps |
| --- | --- | --- | --- |
${rows.join("\n")}
`;
}

if (import.meta.main) {
  const out = render();
  if (process.argv.includes("--check")) {
    const current = (() => {
      try {
        return readFileSync(DOC, "utf8");
      } catch {
        return "";
      }
    })();
    if (current !== out) {
      console.error("docs/jsr-publishing.md is stale — run `bun run jsr:status`.");
      process.exit(1);
    }
    console.log("docs/jsr-publishing.md is up to date.");
  } else {
    writeFileSync(DOC, out);
    console.log(`wrote ${DOC}`);
  }
}
