#!/usr/bin/env bun
/**
 * gen-acs-migrations — embed @bounded-systems/anchored-chain-sqlite's drizzle
 * migration SQL as a string constant (src/migrations.generated.ts).
 *
 * Why generated, not `import x from './m.sql' with { type: "text" }`: JSR rejects
 * the `text` import attribute, so the package couldn't publish. The .sql files
 * stay the source of truth (drizzle uses them on-disk in dev/install); this
 * embeds them so a `bun build --compile` binary (no on-disk ./migrations) can
 * still materialize the schema, AND so the package publishes to JSR. GH-245.
 *
 *   bun run acs:migrations          # write migrations.generated.ts
 *   bun run acs:migrations --check  # fail if stale (CI drift guard)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgSrc = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "anchored-chain-sqlite",
  "src",
);
const migrationsDir = join(pkgSrc, "migrations");
const OUT = join(pkgSrc, "migrations.generated.ts");

interface Journal {
  entries: { tag: string }[];
}

export function render(): string {
  const journal = JSON.parse(
    readFileSync(join(migrationsDir, "meta", "_journal.json"), "utf8"),
  ) as Journal;
  const rows = journal.entries.map((e) => {
    const sql = readFileSync(join(migrationsDir, `${e.tag}.sql`), "utf8");
    return `  ${JSON.stringify(e.tag)}: ${JSON.stringify(sql)},`;
  });
  return `// GENERATED by \`bun run acs:migrations\` (packages/prx/scripts/gen-acs-migrations.ts)
// from packages/anchored-chain-sqlite/src/migrations/*.sql. Do not edit by hand —
// edit the .sql migrations (drizzle's source of truth) and regenerate.
//
// Embeds the migration SQL as a string constant so a \`bun build --compile\` binary
// (no on-disk ./migrations) can materialize the schema, and so the package
// publishes to JSR (which rejects \`with { type: "text" }\` imports). GH-245.

export const EMBEDDED_MIGRATION_SQL: Record<string, string> = {
${rows.join("\n")}
};
`;
}

if (import.meta.main) {
  const out = render();
  if (process.argv.includes("--check")) {
    const current = (() => {
      try {
        return readFileSync(OUT, "utf8");
      } catch {
        return "";
      }
    })();
    if (current !== out) {
      console.error("migrations.generated.ts is stale — run `bun run acs:migrations`.");
      process.exit(1);
    }
    console.log("migrations.generated.ts is up to date.");
  } else {
    writeFileSync(OUT, out);
    console.log(`wrote ${OUT}`);
  }
}
