// GENERATED by scripts/gen-jsr-manifest.ts — do not edit.
// Regenerate: bun run jsr:manifest
//
// jsr-sync imports this static constant instead of reading the filesystem, so
// its outbound requests do not depend on a runtime file read.

export interface JsrPackageMeta {
  name: string;
  scope: string;
  pkg: string;
  description?: string;
  repo: { owner: string; name: string };
  runtimeCompat?: Record<string, boolean | null>;
}

export const JSR_PACKAGES: readonly JsrPackageMeta[] = [
  {
    "name": "@bounded-systems/anchored-chain",
    "scope": "bounded-systems",
    "pkg": "anchored-chain",
    "description": "Derivation chain with contract validation, signing, lineage tracking, and invalidation",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/anchored-chain-sqlite",
    "scope": "bounded-systems",
    "pkg": "anchored-chain-sqlite",
    "description": "SQLite/Drizzle-backed implementation of the anchored-chain stores",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/audit-context",
    "scope": "bounded-systems",
    "pkg": "audit-context",
    "description": "Ambient runtime context for gh-call audit attribution (verb, actor, truth reason)",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/auth",
    "scope": "bounded-systems",
    "pkg": "auth",
    "description": "Service-credential resolver (GitHub, Notion) through a single sanctioned access point",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/bd",
    "scope": "bounded-systems",
    "pkg": "bd",
    "description": "Typed interface to the beads CLI with policy enforcement and short-ID guards",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/cas",
    "scope": "bounded-systems",
    "pkg": "cas",
    "description": "Content-addressable storage substrate: bytes addressed by their SHA-256 digest, with a storage-agnostic blob-store port.",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "node": true,
      "deno": true,
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/disposition",
    "scope": "bounded-systems",
    "pkg": "disposition",
    "description": "Pure classifier mapping work-unit surface state to a disposition (ok/prune/repair/review)",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/env",
    "scope": "bounded-systems",
    "pkg": "env",
    "description": "The one sanctioned reader of process.env, routing ambient config through capability imports",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/fs",
    "scope": "bounded-systems",
    "pkg": "fs",
    "description": "Filesystem capability seam; the one allowed filesystem-access point with an injectable FileSystem",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/gh",
    "scope": "bounded-systems",
    "pkg": "gh",
    "description": "GitHub CLI wrapper with policy enforcement, rate-limit gating, and budget audit logging",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/git",
    "scope": "bounded-systems",
    "pkg": "git",
    "description": "Git CLI wrapper with policy enforcement and stale-lock recovery",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/github-budget",
    "scope": "bounded-systems",
    "pkg": "github-budget",
    "description": "Rate-limit-aware gh wrapper with bucket classification, pre-call gating, and audit trail",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/host",
    "scope": "bounded-systems",
    "pkg": "host",
    "description": "The one sanctioned reader of host/OS ambient state (home dir, temp dir, hostname), routing ambient authority through capability imports",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/machine-schema",
    "scope": "bounded-systems",
    "pkg": "machine-schema",
    "description": "Brands, handoff envelope, and state/phase/invariant primitives for work-unit machines",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/policy",
    "scope": "bounded-systems",
    "pkg": "policy",
    "description": "Tool-policy engine enforcing subcommand allowlists by tool, state, and role",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/proc",
    "scope": "bounded-systems",
    "pkg": "proc",
    "description": "The one allowed subprocess spawn point, routing external-tool invocations through a capability",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/prx-config",
    "scope": "bounded-systems",
    "pkg": "prx-config",
    "description": "TUI configuration schema parser/emitter for L1 Claude and L2 Warp tools",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/repo-root",
    "scope": "bounded-systems",
    "pkg": "repo-root",
    "description": "Repo-root resolution capability: lazy git-based runtime root plus the eager .git-marker walk for build/codegen, the one sanctioned root-resolution point",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/scout",
    "scope": "bounded-systems",
    "pkg": "scout",
    "description": "Content-addressed surface reads (file/grep/files) with anchored-chain provenance",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/slack",
    "scope": "bounded-systems",
    "pkg": "slack",
    "description": "Policy-gated, provenance-tracked Slack read surface: bounded read ops behind a swappable transport port, with keymaker-minted scoped credentials",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/surface-sync",
    "scope": "bounded-systems",
    "pkg": "surface-sync",
    "description": "Type ontology for work-unit change-detection across GH/branch/worktree/tmux/beads",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  },
  {
    "name": "@bounded-systems/verbspec",
    "scope": "bounded-systems",
    "pkg": "verbspec",
    "description": "Spec-driven CLI core: author a verb once as a typed VerbSpec, project it to CLI, MCP, OpenAPI, and Anthropic tool surfaces",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    },
    "runtimeCompat": {
      "bun": true
    }
  }
];
