// GENERATED by scripts/gen-jsr-manifest.ts — do not edit.
// Regenerate: bun run jsr:manifest
//
// jsr-sync imports this static constant instead of reading the filesystem, so
// its outbound requests do not depend on a runtime file read.

export interface JsrPackageMeta {
  name: string;
  scope: string;
  pkg: string;
  description?: string;
  repo: { owner: string; name: string };
  runtimeCompat?: Record<string, boolean | null>;
}

export const JSR_PACKAGES: readonly JsrPackageMeta[] = [
  {
    "name": "@bounded-systems/prx-config",
    "scope": "bounded-systems",
    "pkg": "prx-config",
    "description": "TUI configuration schema parser/emitter for L1 Claude and L2 Warp tools",
    "repo": {
      "owner": "bounded-systems",
      "name": "prx"
    }
  }
];
