#!/usr/bin/env bun
/**
 * rebrand — deterministic npm-scope rename codemod.
 *
 * Replaces the scope prefix `<old>/` -> `<new>/` across source, config, and
 * docs. Package *short* names (cas, proc, …) are unchanged, so this is a
 * single-token prefix replace — the only safe, mechanical part of a scope
 * rename (import specifiers, package.json "name"/deps, and tsconfig paths must
 * be static string literals, so they can't be symbolized).
 *
 * Usage:  bun scripts/rebrand.ts [oldScope] [newScope]
 *   defaults: @prx -> @bounded-systems
 *
 * After running: `bun install` to regenerate the lockfile + relink the
 * workspace under the new scope, then `bun run typecheck` + `bun test`.
 *
 * Deliberately skipped:
 *   - the lockfile (regenerated by `bun install`)
 *   - spikes/ (self-contained throwaway POC, isolated from the workspace)
 *   - the rename meta-docs, which reference the old scope as "the name being
 *     renamed" — replacing there would mangle the migration description.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const oldScope = process.argv[2] ?? "@prx";
const newScope = process.argv[3] ?? "@bounded-systems";
const root = process.cwd();

// Skipped anywhere they appear (by directory basename).
const SKIP_DIRS = new Set([".git", "node_modules", "dist"]);
// Skipped only at this exact repo-relative path (the self-contained throwaway
// POC) — must NOT also catch docs/spikes/, which holds real spike docs.
const SKIP_PATHS = new Set(["spikes"]);
const SKIP_FILES = new Set([
  "bun.lock",
  "scripts/rebrand.ts",
  "docs/roadmap/prx.md",
  "docs/roadmap/rebrand-kickoff.md",
]);
const EXTS = new Set([".ts", ".tsx", ".json", ".md"]);

const find = `${oldScope}/`;
const repl = `${newScope}/`;

let fileCount = 0;
let occCount = 0;
const changed: string[] = [];

function walk(dir: string): void {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    const rel = relative(root, full);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (!SKIP_PATHS.has(rel)) walk(full);
      continue;
    }
    if (SKIP_FILES.has(rel)) continue;
    const dot = name.lastIndexOf(".");
    const ext = dot >= 0 ? name.slice(dot) : "";
    if (!EXTS.has(ext)) continue;
    const src = readFileSync(full, "utf8");
    if (!src.includes(find)) continue;
    const n = src.split(find).length - 1;
    writeFileSync(full, src.split(find).join(repl));
    fileCount += 1;
    occCount += n;
    changed.push(`${rel} (${n})`);
  }
}

walk(root);
console.log(`rebrand ${find} -> ${repl}`);
console.log(`files changed: ${fileCount}, occurrences: ${occCount}`);
for (const c of changed) console.log(`  ${c}`);
