/**
 * Podman driver (prx-asr) — render a {@link PodSpec} to a Kubernetes Pod
 * manifest for `podman kube play`, mirroring the executor's Lima driver
 * (`executor/lima.ts` → `renderLima`): plain text built field-by-field for our
 * known schema (no YAML dependency, readable result), validated at the seam.
 *
 * The mapping:
 *   - each room → a container (sharing the pod's namespaces, the podman-pod
 *     property that makes the door sockets reachable across rooms);
 *   - the door fabric (`doorDir`) → one shared `emptyDir{ medium: Memory }`
 *     (tmpfs) volume mounted into every container, so the unix-socket doors live
 *     on shared memory, not a disk or the network;
 *   - each container's env → {@link podRoomEnv} for that room — the wired-door
 *     projection, i.e. `PRX_BEADS_DOOR`/`PRX_BEADS_SOCKET` for the beadsd
 *     consumer. A closed/unresolved door contributes no env (it isn't wired).
 *
 * The container *image* is not in the RoomSpec yet (the room is the isolation
 * unit; the `-box` image that fills it is a separate concern — prx-zj8). Until
 * that lands, the image is rendered as a deterministic placeholder ref and a
 * TODO; everything else is real.
 */

import { PodSpecSchema, podRoomEnv, type PodSpec } from "./pod.ts";

/** A YAML double-quoted scalar — JSON string syntax is a valid YAML 1.2 scalar. */
function dq(value: string): string {
  return JSON.stringify(value);
}

/** The shared door-fabric volume name. */
const DOOR_VOLUME = "prx-doors";

/**
 * A pod driver: render a {@link PodSpec} to its native orchestration config.
 * Mirrors `ExecutorDriver` — adding a driver must not touch the room/pod specs.
 */
export interface PodDriver {
  /** Stable driver id, e.g. `podman`. */
  readonly id: string;
  /** Render the spec to the driver's native config text. */
  render(pod: PodSpec): string;
}

/**
 * Render a {@link PodSpec} to a `podman kube play` Pod manifest. Validates the
 * spec at the seam (throws on a malformed pod) so a bad input never yields
 * half-config.
 */
export function renderPodmanKube(pod: PodSpec): string {
  const p = PodSpecSchema.parse(pod);
  const lines: string[] = [
    "# Generated by prx (pod spec → podman driver, prx-asr). Do not hand-edit.",
    "apiVersion: v1",
    "kind: Pod",
    "metadata:",
    `  name: ${dq(p.name)}`,
    "spec:",
    // The door fabric: one tmpfs shared by every room's container.
    "  volumes:",
    `    - name: ${DOOR_VOLUME}`,
    "      emptyDir:",
    "        medium: Memory",
    "  containers:",
  ];

  for (const room of p.rooms) {
    lines.push(`    - name: ${dq(room.name)}`);
    // TODO(prx-zj8): the room's `-box` image ref. Placeholder until RoomSpec
    // carries an image (or the pod resolves one per room).
    lines.push(`      image: ${dq(`prx/${room.name}:latest`)} # TODO(prx-zj8): real -box image`);
    lines.push("      volumeMounts:");
    lines.push(`        - name: ${DOOR_VOLUME}`);
    lines.push(`          mountPath: ${dq(p.doorDir)}`);

    const env = podRoomEnv(p, room.name);
    const keys = Object.keys(env).sort();
    if (keys.length > 0) {
      lines.push("      env:");
      for (const key of keys) {
        lines.push(`        - name: ${key}`);
        lines.push(`          value: ${dq(env[key]!)}`);
      }
    }
  }

  return lines.join("\n") + "\n";
}

/** The default podman driver. */
export const podmanDriver: PodDriver = {
  id: "podman",
  render: renderPodmanKube,
};
