# GENERATED by `bun packages/prx/scripts/gen-envelope-feature.ts` from the APPROVAL_MATRIX in packages/prx/src/agents/capability_envelope.ts. Do not edit by hand — edit the matrix and regenerate. Drift-checked by packages/prx/test/agents/capability_envelope.test.ts.
Feature: Capability envelope — approval by scope × reversibility
  As the operator of a capability-scoped agent
  I want approval to escalate with an action's scope and reversibility
  So that hard-to-reverse, outward-facing actions are gated, not assumed

  Rule: approval escalates with scope × reversibility

    Scenario Outline: <scope> + <reversibility> needs <approval> (journaled: <journal>)
      Given an action with scope "<scope>"
      And reversibility "<reversibility>"
      When the capability envelope is evaluated
      Then approval_required is "<approval>"
      And it is journaled: <journal>

      Examples:
      | scope    | reversibility | approval | journal |
      | local    | reversible    | none     | false   |
      | local    | recoverable   | none     | false   |
      | local    | destructive   | notify   | true    |
      | local    | irreversible  | explicit | true    |
      | repo     | reversible    | none     | false   |
      | repo     | recoverable   | notify   | true    |
      | repo     | destructive   | explicit | true    |
      | repo     | irreversible  | explicit | true    |
      | org      | reversible    | notify   | true    |
      | org      | recoverable   | explicit | true    |
      | org      | destructive   | explicit | true    |
      | org      | irreversible  | explicit | true    |
      | external | reversible    | explicit | true    |
      | external | recoverable   | explicit | true    |
      | external | destructive   | explicit | true    |
      | external | irreversible  | explicit | true    |

  Rule: known effects carry an envelope

    Scenario Outline: the "<effect>" effect needs <approval>
      Given the "<effect>" effect
      When the capability envelope is evaluated
      Then approval_required is "<approval>"

      Examples:
      | effect           | scope/reversibility   | approval |
      | git commit       | local/recoverable     | none     |
      | git push         | repo/recoverable      | notify   |
      | git push --force | repo/destructive      | explicit |
      | gh pr merge      | repo/irreversible     | explicit |
      | gh repo settings | org/irreversible      | explicit |
      | publish release  | external/irreversible | explicit |

  Rule: ambient authority is what this prevents

    Scenario: an org-scope irreversible config change requires explicit approval
      Given the "gh repo settings" effect
      When the capability envelope is evaluated
      Then approval_required is "explicit"
      # this is the `gh api PATCH allow_auto_merge` run with ambient authority
