# GENERATED by `bun run features:render` from @bounded-systems/policy POLICY_TABLE. Do not edit by hand — edit the policy table and regenerate. Drift + faithfulness are checked by packages/prx/test/agents/capability_feature.test.ts.
Feature: Actor capability ownership
  As an auditor of what prx gates
  I want to see which actor owns which privileged tool subcommand
  So that the policy can be reviewed without reading code

  Rule: each privileged tool subcommand is owned by a specific set of actors

    Scenario Outline: "git <subcommand>" is owned by <owners>
      Given the prx policy table
      Then "git <subcommand>" is owned by "<owners>"
      And every actor outside "<owners>" is denied it

      Examples: git writes
      | subcommand  | owners                                      |
      | add         | executor, keeper                            |
      | branch      | planner, executor, reviewer, tester, keeper |
      | bundle      | keeper                                      |
      | checkout    | executor, keeper                            |
      | commit      | executor, keeper                            |
      | commit-tree | keeper                                      |
      | fetch       | planner, executor, reviewer, tester, keeper |
      | merge       | executor, keeper                            |
      | pull        | executor, keeper                            |
      | push        | executor, keeper                            |
      | restore     | executor, keeper                            |
      | switch      | executor, keeper                            |
      | worktree    | executor, keeper                            |
      | write-tree  | keeper                                      |

    Scenario Outline: "gh <subcommand>" is owned by <owners>
      Given the prx policy table
      Then "gh <subcommand>" is owned by "<owners>"
      And every actor outside "<owners>" is denied it

      Examples: gh writes
      | subcommand | owners                                     |
      | comment    | executor, tester, forge                    |
      | create     | executor, forge                            |
      | diff       | planner, executor, reviewer, tester, forge |
      | edit       | executor, forge                            |
      | merge      | forge                                      |
      | ready      | forge                                      |
      | review     | planner, reviewer, tester, forge           |

    Scenario Outline: "wt <subcommand>" is owned by <owners>
      Given the prx policy table
      Then "wt <subcommand>" is owned by "<owners>"
      And every actor outside "<owners>" is denied it

      Examples: wt writes
      | subcommand | owners                              |
      | switch     | planner, executor, reviewer, tester |

    Scenario Outline: "bd <subcommand>" is owned by <owners>
      Given the prx policy table
      Then "bd <subcommand>" is owned by "<owners>"
      And every actor outside "<owners>" is denied it

      Examples: bd writes
      | subcommand | owners  |
      | admin      | planner |
      | assign     | planner |
      | claim      | planner |
      | create     | planner |
      | remember   | planner |
      | reopen     | planner |
      | update     | planner |

  Rule: hard-blocked subcommands are owned by no one (denied for every actor)

    Scenario Outline: "<tool> <subcommand>" is hard-blocked
      Given the prx policy table
      Then "<tool> <subcommand>" is denied for every actor

      Examples: hard-blocked
      | tool  | subcommand  |
      | git   | cherry-pick |
      | git   | clean       |
      | git   | clone       |
      | git   | config      |
      | git   | gc          |
      | git   | init        |
      | git   | rebase      |
      | git   | remote      |
      | git   | reset       |
      | gh    | close       |
      | gh    | reopen      |
      | bd    | archive     |
      | bd    | close       |
      | bd    | delete      |
      | bd    | export      |
      | bd    | import      |
      | slack | archive     |
      | slack | create      |
      | slack | delete      |
      | slack | invite      |
      | slack | join        |
      | slack | kick        |
      | slack | leave       |
      | slack | pin         |
      | slack | post        |
      | slack | react       |
      | slack | rename      |
      | slack | schedule    |
      | slack | send        |
      | slack | set         |
      | slack | unpin       |
      | slack | update      |
      | slack | upload      |

  Rule: the capability-poor orchestrator owns nothing

    Scenario: the orchestrator cannot run a privileged tool
      Given the "orchestrator" actor
      When it runs "git push"
      Then the action is denied
