# GENERATED by `bun packages/prx/scripts/gen-cost-visibility-feature.ts` from
# services/anthropic.ts (projectAnthropicUsage, by=workUnitId). Do not edit by
# hand — drift + faithfulness are checked by
# packages/prx/test/services/cost_visibility_feature.test.ts.

Feature: Per-work-unit cost visibility
  As an operator of a fleet of work units
  I want each unit's token usage and USD cost projected from the audit ledger
  So that I can see what every work unit cost, not just an aggregate

  Rule: usage events aggregate to a per-work-unit bucket

    Scenario Outline: <workUnit> usage sums to its own bucket
      Given the recorded usage events
      When usage is projected by workUnitId
      Then <workUnit> shows <calls> calls, <input_tokens> input tokens, and $<total_cost_usd>

      Examples: per-unit cost
      | workUnit | calls | input_tokens | total_cost_usd |
      | GH-1     | 2     | 150          | 0.008          |
      | GH-2     | 1     | 200          | 0.010          |

  Rule: usage with no work unit is still accounted for

    Scenario: an event with no workUnitId groups as "(unattached)"
      Given a usage event with no workUnitId
      When usage is projected by workUnitId
      Then it appears in the "(unattached)" bucket
