# GENERATED by `bun packages/prx/scripts/gen-derivation-chain-feature.ts` from
# @bounded-systems/anchored-chain (digestManifest / canonicalJson / in-toto).
# Do not edit by hand — drift + faithfulness are checked by
# packages/prx/test/provenance/derivation_chain_feature.test.ts.

Feature: Signed content-addressed derivation chain
  As an auditor of prx's provenance chain
  I want each derivation's id to be the hash of its manifest
  So that tampering with a step changes its identity and cannot be laundered

  Rule: a derivation's id is content-addressed — any manifest change changes the id

    Scenario Outline: changing <field> changes the derivation id
      Given the baseline derivation manifest
      When its <field> changes
      Then digestManifest yields a different id

      Examples: manifest fields
      | field     |
      | producer  |
      | inputs    |
      | outputs   |
      | contracts |
      | params    |

  Rule: the id is a deterministic function of content, not key order

    Scenario: the same manifest always yields the same id
      Given the baseline derivation manifest
      Then digestManifest is equal across repeated calls

    Scenario: reordering manifest keys does not change the id
      Given two manifests with identical content but different key order
      Then their canonical JSON — and thus their id — is equal

  Rule: the in-toto statement preserves the manifest

    Scenario: a manifest round-trips through its in-toto statement
      Given the baseline derivation manifest
      When it is converted to an in-toto statement and back
      Then the recovered manifest equals the original
