# GENERATED by `bun run features:render` from @bounded-systems/policy (ownersOf) + provenance/effect-ownership. Do not edit by hand — edit the policy table / verify gate and regenerate. Drift + faithfulness are checked by packages/prx/test/provenance/ownership_feature.test.ts.
Feature: Provenance effect ownership
  As an auditor of what prx verifies after the fact
  I want a signed privileged effect to verify only when its producer owns it
  So that a valid signature alone cannot launder an ambient effect

  Rule: a signed git effect verifies iff produced by an owning actor

    Scenario Outline: a signed "git <subcommand>" verifies only for its owners <owners>
      Given a signed effect derivation for "git <subcommand>"
      Then a derivation produced by one of "<owners>" verifies
      And a derivation produced by any other policy role is rejected as an orphan effect

      Examples: git writes
      | subcommand  | owners                                      |
      | add         | executor, keeper                            |
      | branch      | planner, executor, reviewer, tester, keeper |
      | bundle      | keeper                                      |
      | checkout    | executor, keeper                            |
      | commit      | executor, keeper                            |
      | commit-tree | keeper                                      |
      | fetch       | planner, executor, reviewer, tester, keeper |
      | merge       | executor, keeper                            |
      | pull        | executor, keeper                            |
      | push        | executor, keeper                            |
      | restore     | executor, keeper                            |
      | switch      | executor, keeper                            |
      | worktree    | executor, keeper                            |
      | write-tree  | keeper                                      |

  Rule: a signed effect for a hard-blocked subcommand is always rejected

    Scenario Outline: a signed "git <subcommand>" is rejected though hard-blocked
      Given a signed effect derivation for "git <subcommand>"
      Then verification is rejected for every actor

      Examples: hard-blocked git
      | subcommand  |
      | cherry-pick |
      | clean       |
      | clone       |
      | config      |
      | gc          |
      | init        |
      | rebase      |
      | remote      |
      | reset       |

  Rule: producer identity decides the verdict

    Scenario: a non-policy-role producer passes through (no role to enforce yet)
      Given a signed effect derivation for "git push"
      And its producer actor is a session profile "work"
      Then verification passes through

    Scenario: an unparseable producer is rejected
      Given a signed effect derivation for "git push"
      And its producer builder id is malformed
      Then verification is rejected
