// prx-g88.7 (7a) — the capability ownership policy as a generated, drift-checked
// Gherkin `.feature` (docs/capability-orchestrator.md §5). The external-audit
// surface: a non-engineer (or Aura, for sign-off) can read which actor owns
// which privileged tool subcommand, without reading code. Generated from
// POLICY_TABLE so it cannot drift from enforcement, and the test asserts every
// row matches the table.
//
// Scope: the WRITE subcommands (the ownership boundaries) + the hard-blocks +
// the capability-poor orchestrator. Reads are broadly allowed and not the audit
// interest. (7b will add the scope × reversibility approval envelope.)

import {
  POLICY_ROLES,
  POLICY_TOOLS,
  allowedSubcommands,
  blockedSubcommands,
  isReadOnly,
  ownersOf,
  type PolicyTool,
} from "@bounded-systems/policy";

// The owner-of-effect map is the canonical one in @bounded-systems/policy so the
// guard feature (here) and the verify gate (provenance/effect-ownership) share a
// single source. Re-exported for the existing importers of this module.
export { ownersOf } from "@bounded-systems/policy";

export const CAPABILITY_FEATURE_BANNER =
  "# GENERATED by `bun run features:render` from " +
  "@bounded-systems/policy POLICY_TABLE. Do not edit by hand — edit the policy table " +
  "and regenerate. Drift + faithfulness are checked by " +
  "packages/prx/test/agents/capability_feature.test.ts.";

/** The write (non-read-only) subcommands any role may run for a tool, sorted. */
export function auditedWrites(tool: PolicyTool): string[] {
  const acc = new Set<string>();
  for (const role of POLICY_ROLES) {
    for (const sub of allowedSubcommands(tool, role)) {
      if (!isReadOnly(tool, sub)) acc.add(sub);
    }
  }
  return [...acc].sort();
}

/** Render a Gherkin Examples table with padded columns for readability. */
function examplesTable(headers: string[], rows: string[][]): string[] {
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map((r) => r[i]!.length)),
  );
  const fmt = (cells: string[]) =>
    "      | " + cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ") + " |";
  return [fmt(headers), ...rows.map(fmt)];
}

/** Render the full capability-ownership `.feature`. */
export function generateCapabilityFeature(): string {
  const lines: string[] = [
    CAPABILITY_FEATURE_BANNER,
    "Feature: Actor capability ownership",
    "  As an auditor of what prx gates",
    "  I want to see which actor owns which privileged tool subcommand",
    "  So that the policy can be reviewed without reading code",
    "",
    "  Rule: each privileged tool subcommand is owned by a specific set of actors",
    "",
  ];

  for (const tool of POLICY_TOOLS) {
    const writes = auditedWrites(tool);
    if (writes.length === 0) continue;
    lines.push(
      `    Scenario Outline: "${tool} <subcommand>" is owned by <owners>`,
      `      Given the prx policy table`,
      `      Then "${tool} <subcommand>" is owned by "<owners>"`,
      `      And every actor outside "<owners>" is denied it`,
      "",
      `      Examples: ${tool} writes`,
    );
    const rows = writes.map((sub) => {
      const owners = ownersOf(tool, sub);
      return [sub, owners.length ? owners.join(", ") : "(no one)"];
    });
    lines.push(...examplesTable(["subcommand", "owners"], rows), "");
  }

  // Hard-blocks.
  lines.push(
    "  Rule: hard-blocked subcommands are owned by no one (denied for every actor)",
    "",
    `    Scenario Outline: "<tool> <subcommand>" is hard-blocked`,
    `      Given the prx policy table`,
    `      Then "<tool> <subcommand>" is denied for every actor`,
    "",
    "      Examples: hard-blocked",
  );
  const blockedRows: string[][] = [];
  for (const tool of POLICY_TOOLS) {
    for (const sub of [...blockedSubcommands(tool)].sort()) blockedRows.push([tool, sub]);
  }
  lines.push(...examplesTable(["tool", "subcommand"], blockedRows), "");

  // The capability-poor orchestrator.
  lines.push(
    "  Rule: the capability-poor orchestrator owns nothing",
    "",
    "    Scenario: the orchestrator cannot run a privileged tool",
    '      Given the "orchestrator" actor',
    '      When it runs "git push"',
    '      Then the action is denied',
    "",
  );

  return lines.join("\n");
}
