// prx-g88.7 (7b) — the capability ENVELOPE: scope × reversibility → approval.
//
// 7a made ownership (which actor) auditable. 7b makes the OTHER axis — how much
// approval an action needs — a structured decision table instead of prose
// guardrails ("for actions that are hard to reverse or outward-facing, confirm
// first"). The table is the source of truth; a generated `.feature` projects it
// for review, and a verdict predicate lets a gate consume it.
//
// This is the table-definition slice. Wiring it as an enforced gate (and mapping
// every effect onto it) is a follow-up — but the headline effects below already
// ground it, including the one that opened this whole arc: an org-scope,
// irreversible repo-settings change (the `gh api PATCH allow_auto_merge` I ran
// with ambient authority) lands on **explicit approval**.

export const ENVELOPE_SCOPES = ["local", "repo", "org", "external"] as const;
export const ENVELOPE_REVERSIBILITY = [
  "reversible",
  "recoverable",
  "destructive",
  "irreversible",
] as const;

export type EnvelopeScope = (typeof ENVELOPE_SCOPES)[number];
export type EnvelopeReversibility = (typeof ENVELOPE_REVERSIBILITY)[number];
/** Ascending severity: none < notify < explicit. */
export type Approval = "none" | "notify" | "explicit";

export const APPROVAL_SEVERITY: Record<Approval, number> = {
  none: 0,
  notify: 1,
  explicit: 2,
};

// scope (rows) × reversibility (cols) → approval. Monotonic: severity never
// decreases as either axis increases. Tunable — this matrix IS the policy.
const APPROVAL_MATRIX: Record<EnvelopeScope, Record<EnvelopeReversibility, Approval>> = {
  local: {
    reversible: "none",
    recoverable: "none",
    destructive: "notify",
    irreversible: "explicit",
  },
  repo: {
    reversible: "none",
    recoverable: "notify",
    destructive: "explicit",
    irreversible: "explicit",
  },
  org: {
    reversible: "notify",
    recoverable: "explicit",
    destructive: "explicit",
    irreversible: "explicit",
  },
  external: {
    reversible: "explicit",
    recoverable: "explicit",
    destructive: "explicit",
    irreversible: "explicit",
  },
};

export interface EnvelopeVerdict {
  readonly approval: Approval;
  /** Journaled (NDJSON) iff it needs at least a notify — every non-trivial action. */
  readonly journal: boolean;
}

/** Evaluate the capability envelope for a (scope, reversibility) pair. */
export function evaluateEnvelope(
  scope: EnvelopeScope,
  reversibility: EnvelopeReversibility,
): EnvelopeVerdict {
  const approval = APPROVAL_MATRIX[scope][reversibility];
  return { approval, journal: approval !== "none" };
}

/**
 * Where known effects sit on the two axes — including the ones from this
 * session, so the table is grounded, not abstract. Extend as effects are
 * classified; an unmapped effect has no envelope verdict yet (a learning goal).
 */
export const EFFECT_ENVELOPE: Record<
  string,
  { scope: EnvelopeScope; reversibility: EnvelopeReversibility }
> = {
  "git commit": { scope: "local", reversibility: "recoverable" },
  "git push": { scope: "repo", reversibility: "recoverable" },
  "git push --force": { scope: "repo", reversibility: "destructive" },
  "gh pr merge": { scope: "repo", reversibility: "irreversible" },
  "gh repo settings": { scope: "org", reversibility: "irreversible" },
  "publish release": { scope: "external", reversibility: "irreversible" },
};

const BANNER =
  "# GENERATED by `bun run features:render` from the " +
  "APPROVAL_MATRIX in packages/prx/src/agents/capability_envelope.ts. Do not edit " +
  "by hand — edit the matrix and regenerate. Drift-checked by " +
  "packages/prx/test/agents/capability_envelope.test.ts.";

function table(headers: string[], rows: string[][]): string[] {
  const w = headers.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i]!.length)));
  const fmt = (c: string[]) => "      | " + c.map((x, i) => x.padEnd(w[i]!)).join(" | ") + " |";
  return [fmt(headers), ...rows.map(fmt)];
}

/** Render the capability-envelope `.feature`. */
export function generateEnvelopeFeature(): string {
  const lines: string[] = [
    BANNER,
    "Feature: Capability envelope — approval by scope × reversibility",
    "  As the operator of a capability-scoped agent",
    "  I want approval to escalate with an action's scope and reversibility",
    "  So that hard-to-reverse, outward-facing actions are gated, not assumed",
    "",
    "  Rule: approval escalates with scope × reversibility",
    "",
    "    Scenario Outline: <scope> + <reversibility> needs <approval> (journaled: <journal>)",
    '      Given an action with scope "<scope>"',
    '      And reversibility "<reversibility>"',
    "      When the capability envelope is evaluated",
    '      Then approval_required is "<approval>"',
    "      And it is journaled: <journal>",
    "",
    "      Examples:",
  ];
  const matrixRows: string[][] = [];
  for (const scope of ENVELOPE_SCOPES) {
    for (const rev of ENVELOPE_REVERSIBILITY) {
      const v = evaluateEnvelope(scope, rev);
      matrixRows.push([scope, rev, v.approval, String(v.journal)]);
    }
  }
  lines.push(...table(["scope", "reversibility", "approval", "journal"], matrixRows), "");

  lines.push(
    "  Rule: known effects carry an envelope",
    "",
    '    Scenario Outline: the "<effect>" effect needs <approval>',
    '      Given the "<effect>" effect',
    "      When the capability envelope is evaluated",
    '      Then approval_required is "<approval>"',
    "",
    "      Examples:",
  );
  const effectRows = Object.entries(EFFECT_ENVELOPE).map(([effect, e]) => {
    const v = evaluateEnvelope(e.scope, e.reversibility);
    return [effect, `${e.scope}/${e.reversibility}`, v.approval];
  });
  lines.push(...table(["effect", "scope/reversibility", "approval"], effectRows), "");

  lines.push(
    "  Rule: ambient authority is what this prevents",
    "",
    "    Scenario: an org-scope irreversible config change requires explicit approval",
    '      Given the "gh repo settings" effect',
    "      When the capability envelope is evaluated",
    '      Then approval_required is "explicit"',
    "      # this is the `gh api PATCH allow_auto_merge` run with ambient authority",
    "",
  );

  return lines.join("\n");
}
