// prx-g88.1 — actor sub-agent codegen (the §5 "projection" of the capability
// epic, docs/capability-orchestrator.md). Each policy ROLE projects to one
// `.claude/agents/<role>.md` whose allowlist is generated from the policy table,
// so the human-readable/dispatch surface cannot drift from enforcement. A
// capability-poor `orchestrator` agent is also emitted: it owns NO privileged
// tool and can only delegate.
//
// This is the C1 slice: the projection + a drift test. Runtime enforcement of
// the per-subcommand allowlist is C2 (the PreToolUse policy hook); wiring the
// actor-specific `prx keeper`/`prx publisher` verbs is C2/C3. The generated docs
// here are a faithful projection of POLICY_TABLE — nothing more, nothing less.

import {
  POLICY_ROLES,
  POLICY_TOOLS,
  allowedSubcommands,
  blockedSubcommands,
  type PolicyRole,
} from "@bounded-systems/policy";

/** The generated-file banner — present in every emitted agent doc. */
export const AGENT_GEN_BANNER =
  "<!-- GENERATED by `bun packages/prx/scripts/gen-agents.ts` from " +
  "@bounded-systems/policy POLICY_TABLE. Do not edit by hand — edit the policy " +
  "table and regenerate. Drift is caught by packages/prx/test/agents/generate.test.ts. -->";

/** One-line ownership statement per role (the only hand-authored copy). */
const ROLE_DESCRIPTION: Record<PolicyRole, string> = {
  planner:
    "Planning tier — reads code/issues and writes the plan + bd issues. Owns no git or gh writes.",
  executor:
    "Implements in a worktree — owns git working-tree writes (add/commit/push). No gh merge, no bd writes.",
  reviewer: "Reviews — owns gh PR review. Reads only otherwise.",
  tester: "Validates — reads, plus gh PR comments. No code or ref writes.",
  keeper:
    "Git-write / ref custody — owns push, branch, and the object-graph writers (write-tree/commit-tree). Runs in its own worktree only.",
  forge:
    "GitHub custody — owns ALL gh writes (PR open/ready/merge, issue create/edit, review, labels, comments). Never touches git refs or the working tree.",
};

/** Longer body guidance per role (hand-authored intent; the allowlists below it are generated). */
const ROLE_GUIDANCE: Record<PolicyRole, string> = {
  planner:
    "You draft plans and file/triage bd issues. You do not write code, push, or operate GitHub.",
  executor:
    "You implement the plan in your own worktree and commit/push. You do not open, review, or merge PRs — dispatch that to forge.",
  reviewer:
    "You review PRs and submit gh reviews. You do not commit, push, or merge.",
  tester:
    "You validate and may comment on the PR. You do not commit, push, review, or merge.",
  keeper:
    "You own git refs for one unit, in your own ephemeral worktree. You materialize and push where your branch lives. You never touch gh, bd, or another actor's tree.",
  forge:
    "You own every gh write — PR open/ready/merge, labels, comments, reviews. You never touch git refs (that is keeper) or the working tree.",
};

/** Tools a role can touch (any allowed subcommand), as `prx tools <tool>` Bash globs. */
function roleToolGlobs(role: PolicyRole): string[] {
  const globs: string[] = [];
  for (const tool of POLICY_TOOLS) {
    if (allowedSubcommands(tool, role).length > 0) {
      globs.push(`Bash(prx tools ${tool}:*)`);
    }
  }
  return globs;
}

function renderAllowedSection(role: PolicyRole): string {
  const lines: string[] = [];
  for (const tool of POLICY_TOOLS) {
    const subs = allowedSubcommands(tool, role);
    if (subs.length > 0) lines.push(`- **${tool}** — ${subs.join(", ")}`);
  }
  return lines.length > 0 ? lines.join("\n") : "- _(none — read/delegate only)_";
}

function renderBlockedSection(): string {
  const lines: string[] = [];
  for (const tool of POLICY_TOOLS) {
    const subs = blockedSubcommands(tool);
    if (subs.length > 0) lines.push(`- **${tool}** — ${[...subs].sort().join(", ")}`);
  }
  return lines.join("\n");
}

/** Render the `.claude/agents/<role>.md` content for one policy role. */
export function generateRoleAgentDoc(role: PolicyRole): string {
  const tools = ["Read", "Grep", "Glob", ...roleToolGlobs(role)].join(", ");
  return [
    "---",
    `name: ${role}`,
    `description: ${ROLE_DESCRIPTION[role]}`,
    `tools: ${tools}`,
    "---",
    AGENT_GEN_BANNER,
    "",
    `# ${role}`,
    "",
    ROLE_GUIDANCE[role],
    "",
    "## Allowed subcommands (projected from the policy table)",
    "",
    renderAllowedSection(role),
    "",
    "## Never (hard-blocked, any role)",
    "",
    renderBlockedSection(),
    "",
  ].join("\n");
}

/** The capability-poor orchestrator: no privileged tool, delegate-only. */
export function generateOrchestratorDoc(): string {
  return [
    "---",
    "name: orchestrator",
    "description: Capability-poor — can ONLY delegate to actor sub-agents; owns no privileged tool.",
    "tools: Agent, Read, Grep, Glob",
    "---",
    AGENT_GEN_BANNER,
    "",
    "# orchestrator",
    "",
    "You hold NO privileged capability. You cannot run git, gh, bd, or any",
    "`prx tools` write — you have no Bash at all. Your only move is to DELEGATE to",
    "an actor sub-agent via the Agent tool:",
    "",
    POLICY_ROLES.map((r) => `- **${r}** — ${ROLE_DESCRIPTION[r]}`).join("\n"),
    "",
    "If you find yourself wanting to run an owned effect directly, that is the",
    "ambient-authority anti-pattern (docs/capability-orchestrator.md §1). Delegate",
    "to the owning actor instead.",
    "",
  ].join("\n");
}

/** Every generated agent doc, keyed by its `.claude/agents/<name>.md` basename. */
export function generateAllAgentDocs(): Map<string, string> {
  const docs = new Map<string, string>();
  for (const role of POLICY_ROLES) docs.set(`${role}.md`, generateRoleAgentDoc(role));
  docs.set("orchestrator.md", generateOrchestratorDoc());
  return docs;
}
